godotengine/godot-demo-projects

- 2d/platformer/player.gd
* As soon as the user wants to change direction while in the air, change
the character's facing side.
* This allows for example shooting left then right while in the air and
gives a better feeling.
> Allow changing player facing side while in the air

- 2d/rubegoldberg/engine.cfg
> Rubegoldberg/engine.cfg: Changed the deprecated 'default_density' to 'default_linear_damp'

- 2d/physics_platformer/player.gd
- 3d/kinematic_character/follow_camera.gd
- 3d/platformer/follow_camera.gd
A recent commit to the main Godot engine repo renamed all instances of `pos` with `position` within the Godot API. This PR fixes some compile errors in demo projects that were using the old API names.
> Fix compiler errors after pos to position renames

- 2d/hdr/beach_cave.gd
- 2d/hexagonal_map/troll.gd
- 2d/isometric/troll.gd
- 2d/kinematic_character/colworld.gd
- 2d/kinematic_character/player.gd
- 2d/kinematic_collision/player.gd
- 2d/navigation/navigation.gd
- 2d/physics_platformer/bullet.gd
- 2d/physics_platformer/coin.gd
- 2d/physics_platformer/enemy.gd
- 2d/physics_platformer/moving_platform.gd
- 2d/physics_platformer/player.gd
- 2d/platformer/bullet.gd
- 2d/platformer/coin.gd
- 2d/platformer/enemy.gd
- 2d/platformer/moving_platform.gd
- 2d/platformer/player.gd
- 2d/pong/ball.gd
- 2d/pong/ceiling_floor.gd
- 2d/pong/paddle.gd
- 2d/pong/wall.gd
- 2d/screen_space_shaders/screen_shaders.gd
Testing my half-working GDScript style checker, I corrected the scripts in the 2d section to follow the GDScript style guide. Most of the changes were removing extra () in if statements and adding spaces around operators. Also corrected `get_node` references to `$` syntax.
> GDScript style fixes and other minor corrections

- viewport/3d_in_2d/player.gd
The "3d in 2d" demo wasn't compatible with the current godot version on master.
The player.gd script just seems to use a member of Spatial that got refactored.
> Update 3d in 2d demo for Godot 3.0

- 2d/hdr/beach_cave.tscn
The `WorldEnviroment` background mode has to be `Canvas` for it to work in 2D
> Fixes HDR for 2D demo

- README.md
As people frequently stumble upon that, this points out that you need the appropriate branch for your Godot version.
> README: Different branches for Godot versions

- 3d/platformer/default_bus_layout.tres
Just move it to a reasonable value. Fix #202.
Apparently the setter/getter was [wrong at the beginning](https://github.com/godotengine/godot/blame/70b9aa379d99c78f6db87344e3002808dac70bfa/servers/audio/effects/audio_effect_reverb.cpp#L161-L162) so it might have interfered with this.
> Fix reverb predelay feedback for platformer 3d

- 3d/kinematic_character/cubio.gd
- 3d/kinematic_character/follow_camera.gd
This also strips trailing whitespace in the demo's code – let me know if I should leave them as-is.
This fixes #253.
> Remove an unused variable declaration in Kinematic Character 3D

- 2d/navigation_astar/character.gd
This fixes a minor bug when the astar target_position is the same as the staring point. In that case the path-array has the length of one. The bug is already fixed in @NathanLovato's repository but hasn't been pushed yet.
> checking array length beforehand

- 2d/finite_state_machine/debug/states_stack_displayer.gd
- 2d/finite_state_machine/project.godot
Not effect runtime, just remove some warning spam in editor output.
- Remove autoload non existence script
- Not running state stack display in editor
> Fix finite state demo warning

- viewport/gui_in_3d/Gui_in_3D.tscn
I pulled down the samples and started playing with the 3D GUI and..noticed the GUI was upside down. It was pretty easy to flip it upright, so I thought I'd go ahead and do that and make a pull request. If this isn't the appropriate fix, please advise.
> Updated rotation of Quad to be right side up

- 3d/truck_town/vehicle.gd
Value fwd_mps converts global velocity into a velocity vector which is rotated to cars local coordinate system (in this example x-axis).
Then if key "ui_down" is pressed and the fwd_mps value is greater or equal to -1 (which seems to be very good spot and represents car still moving forward but nearly standing still) the car reverses (negative engine_force_value). If this condition isn't met (which means the car is moving forward) then the car brakes.
Tested and working on Godot 3.1 Beta 3.
Suggestions:
In this case, if you want something more realistic, the -engine_force_value can be much lower because no car reverses in same speed as it goes forward but for the sake of demo project I left it as it is.
Created for my own project with help of user wombatstampede from …
> Automatic brake/reverse

- networking/multiplayer_bomber/gamestate.gd
- networking/multiplayer_bomber/player.gd
We used to broadcast player info on connect and have the server relay it
to other clients.
With this approach, each peer (including server) sends its own info once
to other peers as soon as they connects.
When a new player connects, it is notified of all the already connected
peers by the `network_peer_connected` signal.
Any already connected peer is also notified of the newly connected peer
by the same signal.
References godotengine/godot#18436
> Use p2p in multiplayer bomber player exchange.

- 3d/material_testers/tester.gd
Noticed a lot of error spat out because of non-normalized basis.
I simply followed the suggestion to use `get_rotation_quat()` instead of using constructor of Quat(x).
> Fixed casting from Basis to Quat

- 3d/material_testers/project.godot
Importing ETC2 textures is slow and requires a lot of RAM, so it makes sense to disable it. Those who would like to run the demo on mobile platforms can re-enable it in the Project Settings.
> Disable ETC2 texture compression in the Material Testers demo

- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE.md
- .gitignore
The mono_crash ignore is because they generated anytime there was a crash and I got them often.  
If accepted I will add this to Godot's gitignore file on GitHub's gitignore repo too. @akien-mga 
The rest of the files mirror the main Godot repo, with FUNDING being the exact same, but the ISSUE_TEMPLATE changed to better reflect this repo (questions such as which demo project, etc). We could also eventually add a CODEOWNERS file if we can get people to maintain specific demos.
> Funding and issue template files, and update gitignore

- audio/bpm_sync/Control.gd
- audio/bpm_sync/player.tscn
- audio/bpm_sync/project.godot
- audio/generator/generator.tscn
- audio/generator/generator_demo.gd
- audio/generator/project.godot
- audio/mic_record/MicRecord.gd
- audio/mic_record/MicRecord.tscn
- audio/mic_record/default_bus_layout.tres
- audio/mic_record/default_env.tres
- audio/spectrum/project.godot
- audio/spectrum/show_spectrum.gd
- audio/spectrum/show_spectrum.tscn
A lot of this is just style and typo fixes, but there are also some minor optimizations and renamings, as well as fixing warnings. Also, 3 of the 4 projects were lacking a `config/name`, so I added them.
Note: The BPM Sync demo requires Godot 3.2. I still made some improvements to it, but it doesn't actually work in 3.1.1. We can remove the BPM Sync demo in the 3.1 branch after 3.2's release.
> Update Audio demos for Godot 3.1.1

- misc/pause/pause_button.gd
- misc/pause/spinpause.tscn
In this demo, the focus is on the pausing/unpausing of the SceneTree, so I removed the signal connections and popup thingies to ensure that the only thing that should pick the attention is how to pause/unpause a game in Godot. I also explain how to ensure that there is a safe node that will still process and allow for the scene to unpause.
> Improve Pause demo

- LICENSE.md
- README.md
Error #404: 3.1 branch not found. Let's fix that!
As of this README update, the `master` branch will use Godot 3.2, and we will create a 3.1 branch from the merge commit of this PR. @akien-mga 
The README and LICENSE files were also updated for the older branches in #402 and #403 (these have minimal changes to the license for simplicity, also I merged them in advance, hope that's fine), and see also https://github.com/godotengine/tps-demo/pull/47.
This also closes #389
> Update README and LICENSE for Godot 3.2

- 3d/ik/addons/sade/ik_fabrik.gd
- 3d/ik/addons/sade/ik_look_at.gd
- 3d/ik/addons/sade/plugin.cfg
- 3d/ik/fabrik_ik.tscn
- 3d/ik/fps/fps_example.tscn
- 3d/ik/look_at_ik.tscn
- 3d/ik/project.godot
- 3d/ik/skeleton_ik.tscn
- 3d/ik/skeleton_ik_runner.gd
- 3d/ik/target_from_mousepos.gd
This PR fixes the Godot IK demo so that it works with the recently released Godot 3.2.
This should partially close #375.
I could add a scene using the SkeletonIK node if desired.
______________________
The first issue was that the `set_bone_global_pose` function was renamed to `set_bone_global_pose_override` and a few new arguments were added. This was a simple fix. The only thing to note is that now the `set_bone_global_pose_override` function has a weight/interpolation value, which I set to `1` in this demo.
The second issue is a slight change in how the `set_bone_global_pose_override` function works. Prior to Godot 3.2, when you changed the transform of a bone in a Skeleton, all of the children bones would update and *stay connected* to each other. However, in Godot 3.2 with a weight …
> Fixed GDScript IK demo so it works with Godot 3.2

- 2d/platformer/project.godot
- 2d/platformer/src/Actors/Player.gd
- 2d/platformer/src/Actors/Player.tscn
- 2d/platformer/src/Level/Level.gd
- 2d/platformer/src/Level/Level.tscn
- 2d/platformer/src/Level/Music.gd
- 2d/platformer/src/Main/Game.gd
- 2d/platformer/src/Main/Game.tscn
- 2d/platformer/src/Main/Splitscreen.tscn
- 2d/platformer/src/UserInterface/PauseMenu.gd
Fixes #224, supercedes #270.
I think the best approach to getting a (traditional) splitscreen demo is simply to add a splitscreen mode to the 2D platformer, so I did it. The player is now located outside of the Level scene, making it easy to control how many players there are, and Level sets up the camera bounds for all players.
The splitscreen mode is in a separate scene, and you can swap between them using the Tab key. The two Viewports are in an HSplitContainer with the slider hidden, but it can be easily changed to collapsed, or to shown if you want to change the ratio. It's set up such that it should be fairly easy to expand to 4 players if someone wanted to do so.
This also fixes a bug with controllers where the player sprite would be scaled really thin since the code seemed to …
> Add a splitscreen mode to the 2D platformer.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Improve the comments in the issue template, and the PR template is entirely one comment.
Both mention working with the latest stable version, closes #440.
> Improve the issue template and add a PR template

- 2d/dodge_the_creeps/README.md
- 2d/dodge_the_creeps/attributions.txt
- mono/dodge_the_creeps/README.md
Previously there was a separate `attributions.txt` file, but I think this information is better to have placed in the README file.
Also, Dodge the Creeps with C# was missing copyright statements at all, so technically it was violating copyright if you were to download that project without including the GDScript version that has the copyright statements (such as distribution via the asset library...).
> Move Dodge the Creeps license information into the README files

- misc/multitouch_view/TouchHelper.gd
- misc/multitouch_view/project.godot
- visual_script/multitouch_view/TouchHelper.gd
* Enable touch input from mouse emulation in the GDScript version.
* Fix `return true` etc from a void function. Instead, set input as handled.
* Style tweaks.
> Multitouch View tweaks

- 3d/truck_town/vehicle.gd
Replaced:
```
if steer_target < steer_angle:
steer_angle -= STEER_SPEED * delta
if steer_target > steer_angle:
steer_angle = steer_target
elif steer_target > steer_angle:
steer_angle += STEER_SPEED * delta
if steer_target < steer_angle:
steer_angle = steer_target
steering = steer_angle
```
with
`	steering = move_toward(steering, steer_target, STEER_SPEED * delta)`
> simplifying steering to a single line with move_toward

- viewport/screen_capture/screen_capture.gd
This is to fix #345. It simply changes a double yield in the Viewports tutorial to be a single yield with "frame_post_draw" instead.
> Update Viewports tutorial to use "frame_post_draw"

- 2d/finite_state_machine/player/bullet/bullet_spawner.gd
- 2d/finite_state_machine/player/player_state_machine.gd
- 2d/finite_state_machine/player/weapon/sword.gd
- 2d/finite_state_machine/state_machine/state_machine.gd
- 2d/hdr/beach_cave.gd
- 2d/navigation/navigation.gd
- 2d/navigation_astar/character.gd
- 2d/navigation_astar/pathfind_astar.gd
- 2d/platformer/assets/art/tileset/tileset.tres
- 2d/platformer/project.godot
- 2d/platformer/src/Main/Game.gd
- 3d/ik/fps/example_player.gd
- 3d/ik/fps/weapon_pistol.dae.import
- 3d/ik/godot_battle_bot.dae.import
- 3d/navmesh/navmesh.gd
- misc/window_management/control.gd
- misc/window_management/observer/observer.gd
- viewport/3d_scaling/hud.gd
- viewport/gui_in_3d/gui_3d.gd
Closes #344. All instances of `_input` were replaced with `_unhandled_input` except for the instances where it is used for controlling an FPS camera (Voxel, IK, and WM demos).
This also serves as a PR for updating and testing some projects with Godot 3.2.2 (beta 4).
> Replace _input with _unhandled_input in most places

- 3d/ik/skeleton_ik.tscn
Fixed bug in the IK demo where the SkeletonIK scene would print an error. The issue is that the target nodes are initialized after the SkeletonIK node. Moving the nodes fixed the issue and now no more errors are printed.
> Godot 3.2 IK demo SkeletonIK error fix

- 2d/platformer/assets/theme/fonts/kenney_mini_square.tres
- 2d/platformer/assets/theme/user_interface.tres
Pixel fonts look best when antialiasing is disabled.
> Disable antialiasing on the font in the 2D platformer demo

- misc/multitouch_view/TouchHelper.gd
- visual_script/multitouch_view/TouchHelper.gd
This method incremented a number for every item in `state.keys()` and then returned it. That's the same as `state.keys().size()`, and `state.size()` is the same as that, so we can just replace the helper method with `state.size()`.
> Remove useless "_find_free_pointer_id" method in Multitouch View

- 3d/physics_tests/tests.gd
- 3d/physics_tests/tests/performance/test_perf_contacts.gd
- 3d/physics_tests/tests/performance/test_perf_contacts_extended.tscn
This is a test that demonstrates improvement of multi-core bullet physics. It can also reliably crash my test code, but it works on 3.2 stable.
Was asked by @aaronfranke, but it needs work.
Changes the number of items dropped and drops the previous count but 16 times extra.
> Add extended physics tests.

- 3d/voxel/menu/debug.gd
I recently added this to the TPS demo's debug menu, so I figured I would add it to the Voxel demo too.
> Add memory usage to the Voxel demo

- mobile/android_iap/iap_demo.gd
- mono/android_iap/GodotGooglePlayBilling/BillingResult.cs
- mono/android_iap/Main.cs
After this PR https://github.com/godotengine/godot-google-play-billing/pull/6 "Response Code" can return null.
I made a tine update on the GDscript since if it comes with null vale the interpolation with %d fails. And I chanced the C# version to nullable enum. And I update the messages for test purpose.
> Android IAP Response Code can now return null.

- 2d/dodge_the_creeps/project.godot
- mono/dodge_the_creeps/README.md
Fix incorrect text in the project description and fix the copying section in the C# version's README.
> Fix minor problems with Dodge the Creeps metadata

- networking/multiplayer_bomber/gamestate.gd
- networking/multiplayer_pong/logic/lobby.gd
- networking/websocket_multiplayer/script/main.gd
Always keep a reference to the last used peer even when removing it
from tree.
Fixes godotengine/godot#33290
> Avoid freeing network peer during signal emission.

- .github/FUNDING.yml
The community health files are now available in the godotengine/.github repository, which makes them apply to all repositories in the organization automatically.
See https://github.com/godotengine/godot/issues/40972.
> Remove funding information to use the @godotengine default

- misc/os_test/MonoTest.cs
- misc/os_test/Operating System Testing.csproj
- misc/os_test/Operating System Testing.sln
- misc/os_test/os_test.gd
- mono/2.5d/2.5D Demo with C#.csproj
- mono/README.md
- mono/android_iap/Android in-app purchases with C#.csproj
- mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
- mono/pong/Pong with C#.csproj
* Open and save C# projects to update `csproj` files to Godot 3.2.3.
* Tweak the `MonoTest.cs` file to remove test cases for the removed C# preprocessor defines in Godot 3.2.3.
> Update C# demos for Godot 3.2.3

- mono/dodge_the_creeps/Dodge the Creeps with C#.csproj
1. restore net472:
```
Sdk is referencing Microsoft.NETFramework.ReferenceAssemblies: https://github.com/godotengine/godot/blob/cc3c671f3b636cbfac9fc74095d5bee753e71ed5/modules/mono/editor/Godot.NET.Sdk/Godot.NET.Sdk/Sdk/Sdk.targets#L18-L33
```
I was mistaken previously because of this one time warning in Rider https://youtrack.jetbrains.com/issue/RIDER-52053
2. restore RootNamespace, since default one contains spaces.
Using default one would cause new added script be invalid, at least as I tried in Rider
> Improve Dodge the Creeps demo

- 2d/gd_paint/paint_control.gd
- 2d/physics_platformer/enemy/enemy.gd
- 2d/platformer/src/Actors/Enemy.gd
- mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
- mono/android_iap/GodotGooglePlayBilling/Purchase.cs
This is a minor style fix to conform to the [GDScript style guide's trailing comma rule](https://docs.godotengine.org/en/latest/tutorials/scripting/gdscript/gdscript_styleguide.html#trailing-comma).
> Add trailing commas to enums

- networking/multiplayer_bomber/gamestate.gd
- networking/multiplayer_bomber/lobby.gd
- networking/multiplayer_bomber/lobby.tscn
- networking/multiplayer_bomber/player.tscn
- networking/multiplayer_bomber/project.godot
- networking/multiplayer_bomber/tileset.tres
- networking/multiplayer_pong/lobby.tscn
- networking/multiplayer_pong/logic/lobby.gd
The instructions will only show when the player is hosting a server.
This also includes a button to get your public IP address.
This partially addresses #535.
> Add instructions for port forwarding in the high-level multiplayer demos

- 2d/README.md
- 2d/screen_space_shaders/README.md
- 2d/sprite_shaders/README.md
- misc/README.md
- misc/os_test/README.md
- mobile/android_iap/README.md
- mono/2.5d/README.md
- mono/README.md
- mono/android_iap/README.md
- mono/dodge_the_creeps/README.md
- mono/multiplayer_pong/README.md
- mono/pong/README.md
- viewport/README.md
- viewport/dynamic_split_screen/README.md
- visual_script/README.md
- visual_script/circle_pop/README.md
- visual_script/multitouch_view/README.md
- visual_script/pong/README.md
A few of the links needed updating, and also the Android IAP READMEs were wrong (one was missing, one was incorrect).
> Fix README files, especially in Android IAP demos

- LICENSE.md
It's now 2021, not 2020, so this PR updates the copyright statements for 2021.
> Update copyright statements for 2021

- 2d/physics_tests/tests.gd
- 2d/physics_tests/tests/functional/test_one_way_collision.gd
- 2d/physics_tests/tests/functional/test_one_way_collision.tscn
- 2d/physics_tests/utils/label_slider_value.gd
- 2d/physics_tests/utils/option_menu.gd
- 2d/physics_tests/utils/slider.gd
Update 2D Physics tests with a new demo to test one way collision.
This test scene is inspired by the "Around the Clock" test made by @madmiraal in https://github.com/madmiraal/godot-gym in order to test this PR: https://github.com/godotengine/godot/pull/42574
Like the original test, it allows testing collision between a rigid/kinematic body object and a one-way collision platform at different angles.
This new version is a bit different to be able to use it in a more practical way within the physics test framework:
- There are options and sliders to set different test cases (kinematic or rigid body, platform size, etc.)
- You can still test all angles around the clock, but you can also test only one particular case for debug purpose
- When all angles have been tested, the log gives you …
> Add One Way Collision for 2D Physics tests

- 2d/physics_tests/project.godot
- 2d/physics_tests/test.gd
- 2d/physics_tests/tests/performance/test_perf_broadphase.gd
- 2d/physics_tests/tests/performance/test_perf_broadphase.tscn
- 3d/physics_tests/main.tscn
- 3d/physics_tests/test.gd
- 3d/physics_tests/tests/performance/test_perf_broadphase.gd
- 3d/physics_tests/tests/performance/test_perf_broadphase.tscn
Improvements and fixes for broadphase performance tests in 2D/3D.
- Start logging physics tick one frame earlier for each operation
- Disable debug collision to avoid rendering bottleneck
- Fixes in adding/removing bodies to avoid bottlenecks outside of physics
- 2D: Increase message queue size to allow adding more objects at once
- 3D: Remove camera to disable rendering altogether
- 3D: Fix error with create_rigidbody_box missing default value
> Update broadphase performance test in physics tests

- 2d/physics_tests/main.tscn
- 2d/physics_tests/project.godot
- 3d/physics_tests/main.tscn
- 3d/physics_tests/project.godot
Changed debug collision shortcut from 'D' to 'C' to keep WASD available for other functions in some tests.
Unbound arrows from UI shortcuts for the same reason.
Based on https://github.com/godotengine/godot-demo-projects/pull/577#discussion_r562879147.
> Changed key bindings in physics tests 2D/3D

- misc/joypads/joypads.gd
- misc/joypads/joypads.tscn
- misc/joypads/project.godot
- misc/joypads/remap/joy_mapping.gd
- misc/joypads/remap/remap_wizard.gd
- misc/joypads/remap/remap_wizard.tscn
Most of the code is in the remap folder, but it depends on the gamepad
diagram scene.
It allows remapping of pads to values that godot can understand.
It also comes with some default mapping for the HTML5 platform.
See godotengine/godot#45078
> [Joypads] Add SDL config re-mapping tool.

- viewport/3d_scaling/README.md
- viewport/3d_scaling/hud.gd
- viewport/3d_scaling/hud.tscn
- viewport/3d_scaling/project.godot
It turns out using a TextureRect node isn't necessary :slightly_smiling_face: 
I found this out while working on https://github.com/RodZill4/material-maker/pull/284.
The typical ViewportContainer + Viewport setup can be used just fine to enable filtering on the ViewportTexture returned by the Viewport.
The performance of the new method is equivalent to the old one.
> Simplify the 3D scaling demo setup, enable filtering by default

- 3d/truck_town/car_base.tscn
- 3d/truck_town/car_select.gd
- 3d/truck_town/car_select.tscn
- 3d/truck_town/follow_camera.gd
- 3d/truck_town/project.godot
- 3d/truck_town/tow_truck.tscn
- 3d/truck_town/trailer_truck.tscn
- 3d/truck_town/vehicle.gd
- Increase movement and steering speed significantly.
- Increase gravity slightly for a less floaty feeling.
- Simplify camera code (height is now constant).
- Tweaked camera distance and height to fit each vehicle.
- Fix script error when pressing Escape in the main menu (the demo will now quit).
> Improve controls and camera handling in the Truck Town demo

- 3d/ik/addons/sade/ik_look_at.gd
a slider with a range of 0 - 1 will now appear in the editor. Control of the bone is interpolated between the original bone rotation and the IK lookat rotation. In my opinion, this is basic functionality that should have been included in the first place, seeing as the Godot built in IK node has an interpolation slider.
> Added interpolation functionality to ik_look_at node

- 3d/kinematic_character/player/cubio.gd
This is more flexible, and more importantly, fixes something I missed earlier.
> Set the reset position from the initial start position in KC3D

- misc/joypads/joypad_diagram.tscn
- misc/joypads/joypads.gd
- misc/joypads/joypads.tscn
This should fix #596. The GridContainer of buttons has been increased to the range of 0 to 23 (even though it only goes to 22 in 3.2.4, it looks nicer to have a multiple of 8), and there is another hard limit on the controller diagram so that it doesn't go above 16 (perhaps we can add some things to the diagram, but I don't know where these extra buttons are supposed to map to). I also made it so that it gets children by index instead of by name.
@snougo Can you test this in both 3.2.3 and 3.2.4? Ideally it should work on both.
> Handle up to 24 joypad buttons in the Joypads demo

- misc/os_test/os_test.gd
Fixes #603.
Calls `OS.open_midi_inputs()` before `OS.get_connected_midi_inputs()` and then close MIDI inputs.
> Fix MIDI devices scanning

- .editorconfig
- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature---enhancement-request.md
- 2d/physics_tests/README.md
- 3d/physics_tests/README.md
- README.md
- networking/webrtc_signaling/README.md
This PR updates the README for Godot 3.3 and a few other misc things.
After this PR, there will be a 3.2 branch, and the master branch of the demos will be targeting Godot 3.3.x.
> Update README for the new 3.2 branch

- README.md
This PR updates the README of the 3.2 branch to reflect the changes in #607 and the other PRs linking to there. This is a very small change over #607, it just bolds and italicizes ***3.2***, and changes the download link to point to 3.2 instead of master.
> [3.2] Update README for the new 3.2 branch

- 2d/physics_tests/tests/functional/test_shapes.tscn
- 3d/physics_tests/test.gd
- 3d/physics_tests/tests/functional/test_collision_pairs.tscn
- 3d/physics_tests/tests/functional/test_raycasting.tscn
- 3d/physics_tests/tests/functional/test_shapes.tscn
- 3d/physics_tests/tests/performance/test_perf_contacts.tscn
- 3d/physics_tests/tests/performance/test_perf_contacts_extended.tscn
- 3d/physics_tests/utils/exception_cylinder.gd
Fix custom collision shape drawing in physics tests:
CollisionShape debug draw has changed in 3.3 and now requires a body to be rendered, so the trick to display custom physics shapes in the physics tests had to be updated.
Cylinder support:
Now cylinders are supported in Godot Physics, so the exception to avoid spamming errors when cylinders are used can be removed.
Rigid body picking:
Added mouse-picking to Test Shapes in both 2D and 3D.
> Physics Tests 3.3 update

- 2d/physics_tests/test.gd
- 2d/physics_tests/tests.gd
- 2d/physics_tests/tests/performance/test_perf_contact_islands.tscn
- 2d/physics_tests/tests/performance/test_perf_contacts.gd
- 3d/physics_tests/tests.gd
- 3d/physics_tests/tests/performance/test_perf_contact_islands.tscn
- 3d/physics_tests/tests/performance/test_perf_contacts.gd
- 3d/physics_tests/tests/performance/test_perf_contacts.tscn
- Create bodies by duplicating the ones from the scene to allow custom settings on them for testing purpose
- Rename 3D test with multiple groups of bodies "Contact Islands" instead of "Contacts Extended" for clarity
- Added "Contact Islands" test for 2D
- Fixed log spamming with "Contact Islands" tests due to printing log messages for each group of bodies
- Added parameter to randomize spawn positions in order to make contact separation more balanced (avoids artifacts like a huge column for circles in 2D test)
- Using smaller shapes and larger amount of objects by default to test more extreme case
> Update contact tests in physics tests for 2D & 3D

- 3d/physics_tests/test.gd
Using `Shape::get_debug_mesh` instead of the previous hack to draw a mesh instance based on a collision shape.
Needs https://github.com/godotengine/godot/pull/48316 to work (cherry-picked for 3.3.1).
It will be the only option after https://github.com/godotengine/godot/pull/48175 is merged.
> Fix hack to draw shapes in 3D physics tests

- 2d/dodge_the_creeps/project.godot
The "Dodge the Creeps" project settings don't match the settings in the tutorial. In [Project Settings](https://docs.godotengine.org/en/stable/getting_started/step_by_step/your_first_game.html#project-setup) you're instructed to navigate to
**Project** -> **Project Settings** -> **Display** -> **Window** -> **Stretch**
and set
**Mode:** "2d"
**Aspect:** "keep"
This wasn't done so it's possible to go outside the play area by resizing the game. I've changed the demo project to match the tutorial's instructions.
> Fixed project settings to match tutorial

- 3d/physics_tests/utils/rigidbody_ground_check.gd
- 3d/waypoints/waypoint.gd
If not, get the current camera. Implements and closes #605. This isn't really necessary, but it's a simple fix and it's a cheap check.
> Have waypoints check if the camera is current

- loading/multiple_threads_loading/link_button.gd
- loading/multiple_threads_loading/preload.tscn
- networking/webrtc_minimal/link_button.gd
- networking/webrtc_minimal/main.tscn
- viewport/2d_in_3d/2D_in_3D.tscn
- viewport/3d_in_2d/robot_3d.tscn
- viewport/gui_in_3d/default_env.tres
Keeping GDScript files in their own file makes things easier to work with, and should be preferred for the demos.
Also, this PR deletes the strange "func e()" methods. No idea where they came from, but they're useless and now they're gone.
> Replace built-in scripts and delete strange "e" scripts

- 3d/physics_tests/tests/functional/test_moving_platform.gd
- 3d/physics_tests/tests/functional/test_moving_platform.tscn
- 3d/physics_tests/tests/functional/test_rigidbody_ground_check.gd
- 3d/physics_tests/tests/functional/test_rigidbody_ground_check.tscn
- 3d/physics_tests/tests/functional/test_rigidbody_impact.tscn
Added Ray collision shape to these tests.
RigidBody ground check has added floor segment with convex shape, previously only original concave. I noticed that on the original concave floor in Bullet sphere and ray didn't lose ground but on concave they started to flicker. Also added floor segmentation should give extra test points.
The moving platform now has a movement up and down. It will be needed to test the ground connection (Bullet KinematicBody connection is unstable on vertical movement).
> Update impact, rigid groundcheck, moving platform

- mobile/multitouch_cubes/GestureArea.gd
When pressing with two fingers at once and pinching,  an old coordinate contained in the curr_state dictionary gets added to the base_state dictionary, which causes unintended jumps in both scale and rotation. By clearing base_state the script functions as intended.
Behavior before:
https://user-images.githubusercontent.com/40431794/126072155-e75fa0d4-b3ab-460d-9c53-7336dd864285.mp4
Behavior after:
https://user-images.githubusercontent.com/40431794/126072151-c880ea0a-4fd8-47aa-b303-651db64d0705.mp4
> Fix jumps in scale and rotation when pinching

- mono/android_iap/Main.cs
Updated OnPurchaseConsumptionError() method to match with GooglePlayBilling's signal
> Mono IAP signal method definition mismatch.

- mono/android_iap/GodotGooglePlayBilling/GooglePlayBilling.cs
- mono/android_iap/Main.cs
Fixes following issues:
1. Google play billing method(OnGodotGooglePlayBilling_sku_details_query_error) signature in GooglePlayBilling class doesn't match with Godot's android library exposed method
Check: https://github.com/godotengine/godot-google-play-billing/blob/master/godot-google-play-billing/src/main/java/org/godotengine/godot/plugin/googleplaybilling/GodotGooglePlayBilling.java
Line: 236.
2. "OnConnectError" method signature mismatch
> Google play billing method signature mismatch in demo with Godot's android billing plugin method

- networking/multiplayer_bomber/player.gd
- networking/multiplayer_bomber/score.gd
- networking/multiplayer_pong/logic/ball.gd
- networking/multiplayer_pong/logic/pong.gd
- networking/websocket_multiplayer/script/game.gd
The `sync` keyword has been deprecated since Godot 3.1.
> Use `remotesync` instead of the deprecated `sync` in networking demos

- gui/theming_override/test.gd
This fixes a warning of leaked instances.
"WARNING: cleanup: ObjectDB instances leaked at exit (run with --verbose for details).
At: core/object.cpp:2132."
seems to be the Label.new() that was leaked.
> Fix leaked object - Label

- 2d/dodge_the_creeps/HUD.tscn
- 2d/dodge_the_creeps/Main.tscn
- 2d/dodge_the_creeps/project.godot
Change to make the start button shortcut in the 2D Dodge the Creeps demo to be `start_game`, per the update to the tutorial text in https://github.com/godotengine/godot-docs/pull/5383.
This PR should be committed **after** the other one.
> Change start button shortcut to use custom action

- 2d/README.md
- 2d/physics_platformer/README.md
- 2d/physics_platformer/coin/Coin.tscn
- 2d/physics_platformer/enemy/Enemy.tscn
- 2d/physics_platformer/player/Bullet.tscn
- 2d/physics_platformer/player/Player.tscn
- 2d/physics_platformer/project.godot
- 2d/platformer/README.md
- 2d/platformer/project.godot
- 2d/platformer/src/Actors/Enemy.tscn
- 2d/platformer/src/Objects/Bullet.tscn
- networking/README.md
- networking/multiplayer_bomber/README.md
- networking/multiplayer_bomber/bomb.tscn
- networking/multiplayer_bomber/project.godot
This allows those demos to run on a greater range of devices.
Particles2D nodes were converted to CPUParticles2D for compatibility with GLES2.
Physics-Based 2D Platformer demo now uses the same stretch mode as 2D Platformer for consistency.
> Switch 2D Platformer and Multiplayer Bomber demos to GLES2

- .github/dist/footer.html
- .github/workflows/export_html5.yml
It freezes Firefox when I open it.
This PR also fixes the list items not ending in `</li>`
> Don't export global illumination demo to HTML5

- 2d/dodge_the_creeps/README.md
- 2d/dodge_the_creeps/project.godot
- mono/dodge_the_creeps/README.md
- mono/dodge_the_creeps/project.godot
The link was sending to a not found page because the `Your first game` tutorial was moved to the `Your first 2D game` one. Also fix the tutorial name in the Dodge the Creeps project config file.
> Fix broken links for the your first 2D game tutorial

- misc/joypads/joypads.gd
Added alpha effect to joystick sprites via selfmodulator color on the canvasitem.
> Added Alpha effect to joystick indicators

- 2d/dodge_the_creeps/Main.gd
This follows the recommendation from https://github.com/godotengine/godot/issues/45638.
> Dodge the Creeps: Set the physics parameters of the mob before adding it to the scene tree

- viewport/3d_scaling/hud.gd
- viewport/3d_scaling/project.godot
Scaling didn't work after resizing the window. In Godot 4, the
SubViewport also has a size changed signal which should be used instead.
This fixes the issue I was having: #698 
Tested this in the demo project and my personal project, everything seems to work find again.
The main changes were switching the stretch mode to the new Godot 4 mode Canvas_items like @Calinou suggested. And the viewport change should happen on the SubViewport _size_changed as that one updates later compared to the root viewport, which had more control over the size of the SubViewport for some reason. 
Ps.: This is my first pull request ever so I'm not sure if I did a good job explaining everything.
> Fix scaling not working after resizing the window

- 2d/pong/README.md
- 2d/pong/ball.png.import
- 2d/pong/icon.png.import
- 2d/pong/paddle.png.import
- 2d/pong/pong.tscn
- 2d/pong/project.godot
- 2d/pong/separator.png.import
Made the usual changes to the project settings and tested to see if
everything works.
Everything works fine!
Another task which can be checked of #697.
> Tested and Fixed Pong with GDScript Demo for 4.0-dev

- misc/pause/README.md
- misc/pause/icon.png.import
- misc/pause/pause_button.gd
- misc/pause/project.godot
- misc/pause/spinpause.tscn
> Fixing Pause Demo - Object not rotating + 4.0 changes

- loading/autoload/README.md
- loading/autoload/project.godot
- loading/autoload/scene_a.tscn
- loading/autoload/scene_b.tscn
Not really any fixing were required, some data changed between versions
when opening and testing everything. Did some minor changes to the project
settings so the new Godot 4 terms are used.
Everything works fine without problems.
> Prepared Autoload(Singletons) demo for Godot 4

- gui/input_mapping/ActionRemapButton.gd
- gui/input_mapping/InputRemapMenu.tscn
- gui/input_mapping/README.md
- gui/input_mapping/icon.png.import
- gui/input_mapping/project.godot
Edited the project settings to match the new Godot 4 standard and fixed
the script errors which were making it impossible to run this demo.
Now everything works properly for the 4.0-dev version.
Another check that can be added for #697.
I really hope that I'm doing a good job helping to make all these demo's run properly on Godot 4,
if I'm doing anything wrong, please say so I can improve myself.
> Fixed Script Errors for GUI Input Mapping Demo - 4.0-dev

- misc/pause/process_mode.gd
- misc/pause/project.godot
- misc/pause/spinpause.tscn
This adds an OptionButton to change the ProcessMode of the cube's AnimationPlayer to showcase new pause features in 4.0.
> Pause demo: Showcase new pause features in Godot 4.0

- 3d/global_illumination/camera.gd
- 3d/global_illumination/test.tscn
Follow-up to https://github.com/godotengine/godot-demo-projects/pull/718.
This also tweaks the font shadow appearance for better visibility.
> Revert accidental change in camera script in Global illumination demo

- 2d/gd_paint/README.md
- 2d/gd_paint/icon.png.import
- 2d/gd_paint/paint_control.gd
- 2d/gd_paint/paint_root.tscn
- 2d/gd_paint/paint_tools.png.import
- 2d/gd_paint/project.godot
- 2d/gd_paint/tools_panel.gd
Part of #697
Demo is working now in 4.0.
There is only one slight issue, but that has to do with the engine viewport system I think. When saving the picture, the framing isn't always correct, really depends how you scaled the window. This could also be a me issue as I use i3 on linux (Tiling window manager).
But otherwise, it's working perfectly.
> GD Paint Demo Update to 4.0

- 2d/dodge_the_creeps/README.md
- 2d/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
- 2d/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
- 2d/dodge_the_creeps/art/enemySwimming_1.png.import
- 2d/dodge_the_creeps/art/enemySwimming_2.png.import
- 2d/dodge_the_creeps/art/enemyWalking_1.png.import
- 2d/dodge_the_creeps/art/enemyWalking_2.png.import
- 2d/dodge_the_creeps/art/playerGrey_up1.png.import
- 2d/dodge_the_creeps/art/playerGrey_up2.png.import
- 2d/dodge_the_creeps/art/playerGrey_walk1.png.import
- 2d/dodge_the_creeps/art/playerGrey_walk2.png.import
- 2d/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
- 2d/dodge_the_creeps/icon.png.import
- 2d/dodge_the_creeps/project.godot
Going through the demo's mentioned at: #697
to fix and prepare them for 4.0.
It was mentioned that there were minor bugs (errors printing in console), found non of that, only some logs about awaits not being needed (they were needed). Everything works again now and stretch_mode set to canvas_items.
> Making Demo Dodge the Creeps ready for 4.0-dev

- misc/window_management/README.md
- misc/window_management/control.gd
- misc/window_management/icon.png.import
- misc/window_management/project.godot
- misc/window_management/window_management.tscn
Updated to 4.0 everything should work.
Could not test minimize or maximize as those features are not available for my tiling window manager (i3) .
> Window Management Update 4.0

- gui/input_mapping/ActionRemapButton.gd
- gui/input_mapping/ActionRemapButton.tscn
- gui/input_mapping/InputRemapMenu.tscn
- gui/input_mapping/KeyPersistence.gd
- gui/input_mapping/project.godot
Same as #731 to fix #629 but for 4.0-dev instead.
> [4.0-dev] GUI Input Mapping Demo Persistent Key Mapping- Fixes #629

- gui/input_mapping/ActionRemapButton.gd
- gui/input_mapping/KeyPersistence.gd
- gui/input_mapping/project.godot
This pull request fixes https://github.com/godotengine/godot-demo-projects/issues/629 . Now this demo saves the input keys through saving a dictionary. I hope the comments which I made make sense and that they are helpful.
I could not fix the wrong rebase on #731 so I closed that one.
> [3.x] GUI Input Mapping Demo Persistent Key Mapping- Fixes #629

- 2d/gd_paint/paint_root.tscn
- 2d/gd_paint/project.godot
The clipping happened because the panel was see-through.
The saving is also fixed by changing some of the project settings.
To fix the issues from #734
> Fixing GD Paint Issues in 4.0-dev

- misc/window_management/control.gd
- misc/window_management/project.godot
- misc/window_management/window_management.tscn
Fixing the problem which @aaronfranke mentioned in PR #737
Some functions are not present inside of Godot 4.0 so for the time being I commented them out as this demo will probably need more changes by the end of the alpha.
> Fix window management demo for 4.0

- networking/webrtc_signaling/README.md
> Fix typos in `webrct_signalling/README.md`

- 2d/platformer/src/Main/Game.gd
I believe this comment got out-of-date (based on the fact that the `Stage` scene seems like something that was in an older version of the demo: https://github.com/godotengine/godot-demo-projects/blob/81441c42b79e38e54c2bc38acee3205f22431738/2d/platformer/Stage.tscn), so updated the comment to reflect the current state of the demo, along with some other information that I thought a developer might find helpful.
> Docs: 2D Platformer - Update Pause Mode Comments

- loading/threads/README.md
- loading/threads/mona.png.import
- loading/threads/project.godot
- loading/threads/thread.gd
- loading/threads/thread.tscn
This updates and improves the simple background loading demo (the one that doesn't use `load_interactive`). On the list in #697.
In addition to updating for 4.0, I made the following additional changes:
- Make the comments more clear and informative. I removed a few that I thought were just stating the obvious (like one after `return tex` that just says it returns something, or the one that says `ResourceLoader.load` loads a resource). Most of them I kept and just edited for clarity.
- Don't reuse `Thread` objects. According to the documentation, you shouldn't do this, so the demo now waits for the previous thread to finish (if there is one) and makes a new one.
- Add an `_exit_tree` method that makes sure the thread is finished, then frees it.
- Change the order of the methods in the …
> Update loading in a thread demo for 4.0

- networking/websocket_multiplayer/script/game.gd
Disconnected peers were not properly removed from the local peers list.
> [4.0] [WebSocket] Fix peers handling in multiplayer example.

- gui/multiple_resolutions/main.gd
A fix for the `gui/multiple_resolutions` demo which wouldn't launch because it was using the old property name for viewport width/height settings. This led to the `Vector2` constructor being given null values which gave the following error: 
```
main.gd:7 - at function: @implicit_new: "Invalid call. Nonexistent 'Vector2' constructor." 
```
> Fix property name of viewport width/height settings in Multiple resolutions

- gui/gd_paint/paint_control.gd
- gui/gd_paint/tools_panel.gd
Fixes a few method names in `gui/gd_paint` that have changed in Godot 4.0. This makes the demo fully functioning again as far as I can tell.
> Fix method names in GD Paint that have changed in 4.0

- 3d/global_illumination/default_env.tres
- 3d/global_illumination/project.godot
- 3d/global_illumination/test.gd
3.x version of https://github.com/godotengine/godot-demo-projects/pull/758.
- Add reflection probe mode toggle to use Always update mode (slower, but updates in real-time).
- Add SSAO toggle (with halved SSAO intensity to look better in the test scene).
- Tweak DirectionalLight shadow bias parameters to reduce shadow peter panning.
- Enable FXAA and debanding for a better appearance. Debanding is disabled on mobile due to known issues.
> Improve 3D global illumination demo (3.x)

- misc/os_test/actions.gd
- misc/os_test/os_test.gd
Some fixes for the `misc/os_test` demo. One of them is an API change in 4.0 and the other two are platform specific. I wouldn't be surprised if the file URL change could be relevant on Linux also, but I don't have a machine setup to test that.
The demo now works without errors. Tested on beta 12.
> Fix and update the Operating System Testing demo

- misc/joypads/joypad_diagram.tscn
- misc/joypads/joypads.gd
- misc/joypads/joypads.tscn
- misc/joypads/project.godot
- Many of the values in the diagram were out of sync with their current enum values.
- Properly moved triggers from buttons to axes.
- Removed 'Axis 10' (11th axis), we only support 10.
- Removed buttons beyond SDL_MAX.
- Show approximate position for MISC button, though we lack it on the gamepad image.
Couldn't really test the latter as with my Xbox Series gamepad on Linux it errors with:
```
ERROR: Index (int)p_button = 260154452 is out of bounds ((int)JoyButton::MAX = 128).
at: joy_button (core/input/input.cpp:953)
```
But that's a Godot bug.
> Fix joypads demo button/axis mappings for 4.0

- misc/opensimplexnoise/OpenSimplexNoise_Viewer.gd
- misc/opensimplexnoise/OpenSimplexNoise_Viewer.tscn
- misc/opensimplexnoise/project.godot
persistence's spinbox step size was set to 1, breaking the default of 0.5.
changed step size to 0.05 because small changes in this value make a big different (only values 0 to ~2 are relevant).
other fixes I did:
- typo persistance -> persistence
- documentation button led to 404, changed to permanent 3.6 url (I think this is fair since the demo is made with this version and future godot versions might work differently)
- decreased spinbox widths
- increased button sizes to include "3.6" in the doc button name
- increased vbox separation
- centered texture
- ~disabled high dpi since it doesn't actually properly scale on high dpi~
before
after
ps: how is the release on the website handled?
> opensimplexnoise: Fix persistence, tweak documentation URL and layout

- 2d/navigation_astar/character.gd
- 2d/navigation_astar/pathfind_astar.gd
Checks for obstacles before moving character when shift-clicking. Better matches normal clicking behavior for clicking on obstacles.
> Check for obstacle before teleporting player in Grid-based Pathfinding with Astar

- 2d/bullet_shower/bullets.gd
- 2d/dodge_the_creeps/Main.gd
- networking/webrtc_signaling/demo/client_ui.gd
- viewport/dynamic_split_screen/wall_coloring.gd
[@GlobalScope.randomize](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-randomize):
> Note: This function is called automatically when the project is run. If you need to fix the [seed](https://docs.godotengine.org/en/latest/classes/class_%40globalscope.html#class-globalscope-method-seed) to have consistent, reproducible results, use seed to initialize the random number generator.
> Remove unnecessary `randomize()`

- plugins/addons/main_screen/main_screen_plugin.gd
- viewport/gui_in_3d/gui_3d.gd
The existing code for the `gui_in_3d` demo doesn't work on the latest RC, it throws this error:
Error at (39, 18): Could not find type "mouse_event" in the current scope".
I changed it to use get_class and a simple match which works on beta17 and rc5
> Fix "is mount_event" check in gui_in_3d to work with both 4 beta and 4 rc 

- networking/websocket_multiplayer/script/main.gd
We were removing it from the MultiplayerAPI but not immediately destroying it (to avoid tricky in-signal de-referencing). We still need to properly close the connection in this case if we want the remote peer to be notified immediately.
Fixes #793
> [3.x] [WebSocket] Fix peer disconnection not closing the network layer.

- 2d/bullet_shower/project.godot
- 2d/dodge_the_creeps/project.godot
- 2d/instancing/project.godot
- 2d/pong/project.godot
- audio/mic_record/project.godot
- gui/control_gallery/project.godot
- gui/gd_paint/project.godot
- gui/input_mapping/project.godot
- gui/multiple_resolutions/project.godot
- gui/pseudolocalization/project.godot
- gui/translation/project.godot
- misc/pause/project.godot
- misc/window_management/project.godot
See #866. These demos work on Forward+ in master, but READMEs say Vulkan Mobile.
> Fix renamed `vulkan/rendering/back_end=1` setting (Vulkan Mobile)

- 2d/physics_tests/tests.gd
- 2d/physics_tests/tests/functional/test_character.gd
- 2d/physics_tests/tests/functional/test_character_tilemap.gd
- 2d/physics_tests/tests/functional/test_one_way_collision.gd
- 2d/physics_tests/tests_menu.gd
- 2d/role_playing_game/dialogue/dialogue_data/npc.json
- 2d/role_playing_game/dialogue/dialogue_data/object.json
- 2d/role_playing_game/dialogue/dialogue_data/player_lose.json
- 2d/role_playing_game/dialogue/dialogue_data/player_won.json
- 3d/antialiasing/anti_aliasing.tscn
- 3d/material_testers/tester.gd
- 3d/physics_tests/tests.gd
- 3d/physics_tests/tests/functional/test_moving_platform.gd
- 3d/physics_tests/tests_menu.gd
- networking/multiplayer_bomber/player_controls.gd
- networking/websocket_chat/client.gd
- networking/websocket_chat/server.gd
- networking/websocket_chat/websocket/WebSocketClient.gd
- networking/websocket_chat/websocket/WebSocketServer.gd
- plugins/addons/material_import_plugin/import.gd
[GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) recommends the `var name: Type` style (no space before the colon). The same goes for [properties](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html#properties-setters-and-getters) (it's not in the style guide yet, but vnen confirmed it in Rocket Chat).
Related:
* godotengine/godot#74306
* godotengine/godot-docs#6896
> Fix GDScript code style regarding colon (demos)

- loading/serialization/save_load_json.gd
Fix the warning: 
> The function 'stringify()' is a static function but was called from an instance. Instead, it should be directly called from the type: 'JSON.stringify()'.<GDScript Error>STATIC_CALLED_ON_INSTANCE <GDScript Source>save_load_json.gd:37
>  loading/serialization demo fixed to work with Godot 4 stable

- gui/rich_text_bbcode/rich_text_bbcode.tscn
Handler "_on_pause_pressed" has been removed but not the signal from the button.
fix the following runtime error:
> E 0:00:01:0716   emit_signalp: Error calling from signal 'pressed' to callable: 'Control(rich_text_bbcode.gd)::_on_pause_pressed': Method not found.
>		<C++ Source>   core/object/object.cpp:1058 @ emit_signalp()
> disconnect unused signal connected to a removed method

- gui/input_mapping/KeyPersistence.gd
File class object replaced by the new FileAccess class in order to fix the demo for Godot 4 release.
> GUI/InputRemapMenu demo fixed to work with Godot 4 stable

- misc/2.5d/addons/node25d/node_25d.gd
- misc/2.5d/addons/node25d/shadow_math_25d.gd
- misc/2.5d/addons/node25d/y_sort_25d.gd
Just following the rules! 
Moved up the icon statements above the other includes. This got rid of errors preventing plugin from loading.
There's still a race condition when the plugin starts up. It's looking for an editor interface child that hasn't been loaded yet. May want to use _ready to define some behavior before _enter_tree is used.
> Change Icon header ordering for 2.5d GD Script Demo

- 2d/platformer/gui/pause_menu.gd
> Add missing return types in platformer's pause_menu.gd

- 3d/graphics_settings/control.tscn
- 3d/graphics_settings/polyhaven/dutch_ship_medium_1k.gltf.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_arm_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_diff_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_hull_nor_gl_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_arm_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_diff_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_rigging_nor_gl_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_arm_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_diff_1k.jpg.import
- 3d/graphics_settings/polyhaven/textures/dutch_ship_medium_sails_nor_gl_1k.jpg.import
- 3d/graphics_settings/settings.gd
- Fix scripts for Godot 4.0.stable.
- Tweak Low preset (enable FXAA, disable MSAA to improve performance).
- Colorize FPS counter depending on framerate (red = bad, yellow = OK, green = good, cyan = great).
- Use first-class Signal syntax to reduce reliance on strings.
> Update 3D Graphics Settings demo for 4.0

- 3d/platformer/coin/coin.tscn
- 3d/platformer/enemy/enemy.tscn
- 3d/platformer/particle_material.tres
- 3d/platformer/player/bullet/bullet.tscn
- 3d/platformer/player/player.tscn
- Add a visible coin glow around coins to make them more noticeable at a distance.
- Enable Billboard Keep Scale material property on particle draw materials that required it.
- Use transparent additive shading as intended for the bullet trail.
- Tweak blob shadow texture and decal to be slightly more subtle.
> Fix particles in Platformer 3D demo, add coin glow

- networking/websocket_chat/chat.tscn
- networking/websocket_chat/client.tscn
- networking/websocket_chat/combo.tscn
- networking/websocket_chat/project.godot
- networking/websocket_chat/server.tscn
- networking/websocket_chat/websocket/WebSocketClient.gd
- networking/websocket_chat/websocket/WebSocketServer.gd
Old cert + key/servername have been replaced with the new TLSOption configuration object.
The scene changes are just the result of opening the project and re-saving the scene with godot 4.0.2 stable.
> [WebSocket] Fix chat demo to updated TLS function.

- gui/rich_text_bbcode/project.godot
- gui/rich_text_bbcode/rich_text_bbcode.tscn
- Allow toggling pause by pressing the <kbd>Pause</kbd> key, in addition to the existing button.
> Fix typo in Rich Text Label with BBCode

- 3d/squash_the_creeps/Player.gd
Not technically wrong as `Player` is in global space but easily confusing to new users if they keep using `position` for this method.
Related:
* https://github.com/godotengine/godot-docs/pull/7890
> [Squash The Creeps] Use `Basis.looking_at` to control facing

- 3d/voxel/menu/main/main_menu.tscn
- 3d/voxel/project.godot
- 3d/voxel/settings.gd
- 3d/voxel/world/chunk.gd
- See https://github.com/godotengine/godot-demo-projects/issues/697.
Note: I've gotten a crash once after creating a flat world (couldn't reproduce it more than once) on 4.2.dev godotengine/godot@7831eedf1:
```
ERROR: Caller thread can't call this function in this node (/root). Use call_deferred() or call_thread_group() instead.
at: propagate_notification (./scene/main/node.cpp:2218)
```
```cpp
handle_crash: Program crashed with signal 11
Engine version: Godot Engine v4.2.dev.custom_build (7831eedf1c24805e6efdd5b7ee659c2095eaa765)
Dumping the backtrace. Please include this when reporting the bug to the project developer.
[1] /lib64/libc.so.6(+0x3dbb0) [0x7f622165fbb0] (??:0)
[2] godot() [0x83415f2] (/usr/include/c++/13/bits/atomic_base.h:505)
[3] godot() [0x83424e8] …
```
> Update Voxel demo for Godot 4.1.1

- audio/spectrum/project.godot
- audio/spectrum/show_spectrum.gd
The videos are only 30 fps. In the **old version**, changes are even harder to see when 'Spectrum' is updated at over 150 fps.
**old version**
https://github.com/godotengine/godot-demo-projects/assets/41921395/d741eca2-7a20-47a2-a9ba-1dfcfa313952
**new version**
https://github.com/godotengine/godot-demo-projects/assets/41921395/f1a4af4a-326d-47fd-b3d0-bc4720427456
> Audio Spectrum: added smoother animations

- misc/matrix_transform/marker/AxisMarker2D.gd
- misc/matrix_transform/marker/AxisMarker2D.svg.import
- misc/matrix_transform/marker/AxisMarker3D.gd
- misc/matrix_transform/marker/AxisMarker3D.svg.import
- misc/matrix_transform/project.godot
v4.2.dev6.official [57a6813bb]
Matrix Transform _(fix `@icon` statement, must be at the top of script)_ https://github.com/godotengine/godot-demo-projects/issues/697
> Matrix Transform: ported to Godot 4.2

- 2d/finite_state_machine/Demo.tscn
- 2d/finite_state_machine/debug/StatesStackDiplayer.tscn
- 2d/finite_state_machine/project.godot
Move attack map from gamepad Start to X so it's more discoverable.
Change label on state stack. "Pushown" was a typo for "pushdown", but understanding that requires reading a wikipedia page.
Add some periods to Explanations for consistency.
> fsm: Map attack to gamepad X; revise text

- 2d/physics_tests/project.godot
- 2d/physics_tests/tests/functional/test_one_way_collision.gd
- 2d/physics_tests/tests/functional/test_one_way_collision.tscn
v4.1.1.stable.official [bd6af8e0e]
The example is very complex, I am not sure if more changes are needed. (So far I have adjusted only one line)
**"TEST OPTIONS"**:
1.  "Rigid body" -> "RESULT: **PASSED**"
2. "Character body -> **NOT PASSED**"
https://github.com/godotengine/godot-demo-projects/assets/41921395/c84b39b2-5de8-4775-9b81-be6d7f8dc872
> 2D Physics Tests, fixed "one-way collision script error"

- mobile/multitouch_cubes/CubeScene.tscn
- mobile/multitouch_cubes/GestureArea.gd
- mobile/multitouch_cubes/Main.tscn
- mobile/multitouch_cubes/default_env.tres
- mobile/multitouch_cubes/project.godot
v4.1.2.stable.official [399c9dc39]
- **Camera3D**: new `Position` (0, 0, 3)
- **SubViewport**: `Own World 3D`, had to be activated manually after automatic conversion
**Test on Android**
https://github.com/godotengine/godot-demo-projects/assets/41921395/91652c69-584a-41a1-b05f-566b2ffd640e
> Multitouch Cubes: ported to Godot 4.1

- networking/websocket_minimal/Main.tscn
- networking/websocket_minimal/README.md
- networking/websocket_minimal/client.gd
- networking/websocket_minimal/project.godot
- networking/websocket_minimal/server.gd
- `WebSocketServer` and `WebSocketClient` no longer exist from version 4.0 onwards
- The controls are new
https://github.com/godotengine/godot-demo-projects/assets/41921395/bdaed65c-76d5-443c-81b1-ae7ed4171545
> WebSocket Minimal: ported to Godot 4.1

- 2d/dodge_the_creeps/Player.gd
- 2d/dodge_the_creeps/Player.tscn
- 2d/dodge_the_creeps/project.godot
> Fix Trail(GPUParticles2D) in Dodge The Creeps

- 3d/antialiasing/README.md
- 3d/antialiasing/anti_aliasing.tscn
- 3d/antialiasing/project.godot
- Follow-up to https://github.com/godotengine/godot-docs/pull/8481 (can be merged independently).
___
- Add colored planes below some examples to make antialiasing differences easier to see.
- Change various textures to make antialiasing differences easier to see.
> Add alpha antialiasing example to 3D Antialiasing demo

- networking/webrtc_signaling/demo/main.gd
- networking/webrtc_signaling/server/ws_webrtc_server.gd
The check to hide the "Listen" button on Web platforms was not updated from the old 3.x name (HTML5).
> Fix Web platform checks in WebRTC signaling demo

- 2d/dodge_the_creeps/Player.gd
- 2d/dodge_the_creeps/project.godot
using rotation in the player node instead of flipping vertically, by doing so the trail is also rotated
> Fix dodge the creeps vertical movement

- viewport/gui_in_3d/gui_3d.gd
- viewport/gui_in_3d/gui_in_3d.tscn
Rework Gui in 3D Demo to handle mouse events via Physics Picking instead of in _unhandled_input.
This brings several benefits:
- Correctly handle cases, where the 3D-GUI is located behind other collision objects. (currently one can interact with it, even when there is a collision object (e.g. wall) between camera and the 3D-GUI)
- Proper passive hovering support
This allows also to make simplifications in the code, because 3D-mouse position no longer needs to be calculated manually.
This PR does for 3D, what https://github.com/godotengine/godot/pull/58334 did for 2D-SubViewportContainer.
Needs to work correctly https://github.com/godotengine/godot/pull/78383 (included in V4.2)
Updated 2023-08-31: Make sure to include Velocity in `InputEventMouseMotion` when sending event to SubViewport. …
> Rewrite Gui in 3D demo to use Physics Picking for mouse events

- 3d/squash_the_creeps/Mob.tscn
- 3d/squash_the_creeps/Player.gd
- 3d/squash_the_creeps/Player.tscn
I added CollisionShapes for the player and the enemy to fix the bug of the enemy passing through the player.
> Fix squash_the_creeps hitboxes

- 3d/squash_the_creeps/Main.tscn
- 3d/squash_the_creeps/Mob.tscn
- 3d/squash_the_creeps/Player.tscn
This was missed in the upgrade to 4.0, which reset loop mode properties in Animation.
https://github.com/godotengine/godot-demo-projects/assets/180032/6b4fab77-3dc1-40f0-a8a1-0668d740cadd
*Mob animation fix isn't shown on the video, as it was recorded before I pushed an update to this PR.*
https://github.com/godotengine/godot-demo-projects/assets/180032/eabd68b6-a048-4310-8f6f-6ac7c1a07ced
> Fix player and mob animations not looping in Squash the Creeps

- mono/pong/Logic/Ball.cs
- mono/pong/Logic/Paddle.cs
- mono/pong/Pong with C#.csproj
- mono/pong/ball.png.import
- mono/pong/paddle.png.import
- mono/pong/pong.tscn
- mono/pong/project.godot
- mono/pong/separator.png.import
I saw the mono pong demo had been version 4 dev. which cannot build in version 4 because change on dotnet version (4.7 to 6). 
I update and test it.
I did not make any issue.
> Update Pong with C# to Godot 4.2.1

- 2d/dodge_the_creeps/HUD.tscn
- 2d/dodge_the_creeps/fonts/Xolonium-Regular.tres
The fonts were not working in Dodge The Creeps 2D example and there was an error being generated.
This fixes the issue based on how the tutorial explains to set up fronts now
https://docs.godotengine.org/en/latest/getting_started/first_2d_game/06.heads_up_display.html#
I believe the `Xolonium-Regular.tres` file was causing this error:
```
Class 'Font' or its base class cannot be instantiated.
editor/plugins/editor_preview_plugins.cpp:828 - Condition "sampled_font.is_null()" is true. Returning: Ref<Texture2D>()
```
Which appears in both Godot 4.2 and 4.3, although not as readily in 4.2.
The file does not seem to be necessary so I removed it.
> Correct font setup in Dodge The Creeps 2D.

- compute/texture/project.godot
Avoids the bug in https://github.com/godotengine/godot/issues/90363
Multithreaded rendering is not safe in 4.2, so it should not be used in our official demos
> Switch to single safe threaded model in TextureRD demo

- audio/midi_piano/piano.gd
This is a silly "fix", but it prevents an empty `[]` from being printed every time this demo is run without a MIDI device plugged into the computer.
The MIDI devices list is printed if one is plugged into the computer, which I have tested.
> Only print MIDI device list if any are found.

- misc/2.5d/addons/node25d/main_screen/gizmo_25d.gd
- misc/2.5d/addons/node25d/main_screen/gizmo_25d.tscn
- misc/2.5d/addons/node25d/main_screen/main_screen_25d.tscn
- misc/2.5d/addons/node25d/main_screen/viewport_25d.gd
- misc/2.5d/addons/node25d/node25d_plugin.gd
- misc/2.5d/addons/node25d/node_25d.gd
- misc/2.5d/addons/node25d/shadow_math_25d.gd
- misc/2.5d/assets/cube/cube_math.gd
- misc/2.5d/assets/demo_scene.tscn
- misc/2.5d/assets/player/player_25d.tscn
- misc/2.5d/assets/player/player_math_25d.gd
- misc/2.5d/assets/player/player_sprite.gd
- misc/2.5d/assets/shadow/shadow_25d.tscn
- misc/2.5d/assets/ui/overlay.tscn
- misc/2.5d/project.godot
This works now in Godot 4, but I still get this error when it starts:
```
.\scene/main/node.h:445 - Parameter "data.tree" is null.
res://addons/node25d/main_screen/viewport_25d.gd:23 - Invalid access to property or key 'process_frame' on a base object of type 'null instance'.
```
I'm not sure how to fix it though. I feel like there is something hacky about this line, but I'm not sure what the correct solution is:
https://github.com/godotengine/godot-demo-projects/blob/d190e73ad3af67447bb43ebe1ae0bcd01152e149/misc/2.5d/addons/node25d/main_screen/viewport_25d.gd#L20-L22
This should fix:
https://github.com/godotengine/godot-demo-projects/issues/1040
and
https://github.com/godotengine/godot-demo-projects/issues/1016
I did hit the files I edited with the …
> Update 2.5D GDScript demo to display the editor plugin in Godot 4.

- 3d/truck_town/vehicles/follow_camera.gd
Upon starting the project and selecting a truck, this error is always emitted:
```
E 0:00:22:0996   follow_camera.gd:27 @ @implicit_new(): Condition "!is_inside_tree()" is true. Returning: Transform3D()
<C++ Source>   scene\3d\node_3d.cpp:346 @ Node3D::get_global_transform()
<Stack Trace>  follow_camera.gd:27 @ @implicit_new()
car_select.gd:15 @ _load_scene()
car_select.gd:39 @ _on_mini_van_pressed()
```
This also happens if you go back and pick a different truck.
I believe this is caused by attempting to assign `global_position` to a variable before the scene has initialized.
Waiting until the `_ready()` function to assign the variable for the first time appears to solve this issue.
Other fixes I tried fixed the initial error, but the error persisted if you went "Back" and selected a …
> Wait until `_ready` function to init previous_position to prevent errors

- misc/joypads/joypads.tscn
- misc/joypads/project.godot
- misc/joypads/remap/remap_wizard.gd
- misc/joypads/remap/remap_wizard.tscn
This fixes a number of issues preventing to use the remap feature:
- The gamepad images with the button layout were not visible
- Gamepad input was not being detected while the remap window was focused
- Some porting issues where `.pressed` appeared where `.button_pressed` was meant
- The wrong buttons being highlighted when remapping triggers
- The remap window was accepting events from all gamepads rather than only the one being remapped, which could be an issue if another connected controller has analog drift of is accidentally pressed for whatever reason.
~Input detection only works with native subwindows. I couldn't get it to work when using embedded subwindows. The subwindow seems to stop event propagation even with handle_input_locally disabled. You can workaround it by clicking …
> Fix joypad demo for Godot 4.x

- viewport/gui_in_3d/gui_3d.gd
- Godot 3's SpatialMaterial has a "params_billboard_mode" property:
https://docs.godotengine.org/en/3.6/classes/class_spatialmaterial.html#class-spatialmaterial-property-params-billboard-mode
- but Godot 4's BaseMaterial3D instead has a "billboard_mode" property:
https://docs.godotengine.org/en/stable/classes/class_basematerial3d.html#class-basematerial3d-property-billboard-mode
But I guess nobody needed any convincing since that change has already been made at line 20:
`if node_quad.get_surface_override_material(0).billboard_mode == BaseMaterial3D.BillboardMode.BILLBOARD_DISABLED:`
> Fixed minor Godot 3 bit in "gui_in_3d" demo's billboard specific code

- 3d/particles/test.tscn
- Make the attractor in the example dynamic to better showcase its functionality, and add a visual representation to it.
- Tweak the appearance of attracted particles.
- Fix force field particle display (it wasn't using Local Coords as intended).
- Lower the sun angle to make the background darker (and particles easier to see).
https://github.com/godotengine/godot-demo-projects/assets/180032/6e82e6d2-b616-4d35-9754-7db3054bcd61
> Add turbulence example to 3D Particles demo

- 3d/antialiasing/project.godot
- 3d/decals/project.godot
- 3d/global_illumination/project.godot
- 3d/global_illumination/test.tscn
- 3d/kinematic_character/project.godot
- 3d/labels_and_texts/project.godot
- 3d/material_testers/project.godot
- 3d/navigation/project.godot
- 3d/occlusion_culling_mesh_lod/project.godot
- 3d/particles/project.godot
- 3d/physical_light_camera_units/test.tscn
- 3d/procedural_materials/project.godot
- 3d/rigidbody_character/project.godot
- 3d/squash_the_creeps/project.godot
- 3d/variable_rate_shading/project.godot
- 3d/volumetric_fog/project.godot
- 3d/voxel/menu/ingame/pause_menu.tscn
- 3d/voxel/project.godot
- 3d/voxel/world/world.tscn
- 3d/waypoints/main.tscn
- 3d/waypoints/project.godot
- misc/large_world_coordinates/project.godot
- misc/large_world_coordinates/test.tscn
- viewport/3d_scaling/project.godot
The 3D demos aren't very demanding and Godot has been optimized a bit since 4.0's release, so we can afford using higher quality shadow settings for less noisy shadow filtering.
This also tweaks shadow bias to reduce shadow acne in the Voxel demo.
The time slider in the Physical Light and Camera units demo now allows for more precise adjustments.
*Click to view at full size.*
> Use higher shadow filtering quality settings in 3D demos

- .gitignore
For reference, this exists in other godotengine repositories. Examples:
* https://github.com/godotengine/godot/blob/master/.gitignore#L157
* https://github.com/godotengine/godot-docs/blob/master/.gitignore#L52
> Add JetBrains IDE files to .gitignore

- 3d/lights_and_shadows/README.md
The original link is incorrect and points to the [Tween Interpolation Demo](https://godotengine.org/asset-library/asset/2733)
> Fix incorrect asset library link

- 3d/truck_town/vehicles/trailer_truck.tscn
Fixes #1101.
This demo is currently a bit broken when using the semi-truck, as the joint between the truck and the trailer uses a `ConeTwistJoint3D` with a `swing_span` and `twist_span` of 30 and 45 _radians_ respectively. I'm assuming this was meant to be degrees at some point, but something must have changed in Godot since this demo was made, where it no longer saves these properties as degrees. This only happened to work due to `ConeTwistJoint3D` supporting multiple revolutions along the twist axis in Godot/Bullet, but which is not something supported by Jolt.
This PR fixes that by changing over to a 6DOF joint instead, which I would argue is the more intuitive setup for this particular vehicle.
I also changed/improved the collision boxes for both the truck and the trailer, as the …
> Change semi-truck in Truck Town demo to use 6DOF joint

- 3d/ik/addons/sade/ik_fabrik.gd
- 3d/ik/addons/sade/ik_look_at.gd
- 3d/ik/button_change_scene.gd
- 3d/ik/fabrik_ik.tscn
- 3d/ik/fps/example_player.gd
- 3d/ik/fps/fps_example.tscn
- 3d/ik/fps/simple_bullet.gd
- 3d/ik/fps/simple_bullet.tscn
- 3d/ik/look_at_ik.tscn
- 3d/ik/skeleton_ik.tscn
- 3d/ik/target_from_mousepos.gd
This is an initial attempt to convert the 3D Inverse Kinematics demo, related to updating all Demos to Godot 4 Issue #697
The project doesn't entirely work yet, but it runs. I am still working on making it work fully, but at least it starts now instead of crashing and you can cycle through the scenes and read all of the text.
I'll keep updating this when I make more parts work. I leave it up to you if you want to merge it now or wait until I have made it more functional.
I hit some of the files with my code formatter, if white-space updates are not wanted I can remove those.
> 3D Inverse Kinematics Godot 4 Conversion (Partial)

- 2d/navigation_astar/character.gd
- 2d/navigation_astar/pathfind_astar.gd
I was just looking at this demo and realized that jumping to definitions of things would work a little better if the types were filled in, so I went ahead and did it.
Part of https://github.com/godotengine/godot-demo-projects/issues/868
> Add static types in 2D Navigation A Star demo

- 3d/voxel/README.md
Add full license info for voxel textures
Hello,
The textures in the Voxel Demo were included from [Minetest Game](https://github.com/minetest/minetest_game/) ("MTG") for [Minetest](minetest.net/) without "full" attribution of the authors. The attribution information needs to be present since the files are under CC BY-SA 3.0.
Although a general attribution was given to the "Minetest Contributors", I thought it was worth noting the original authors of each file that was used, and noting that some are actually under CC0. This info was supplied in a [README](https://github.com/minetest/minetest_game/blob/master/mods/default/README.txt).
Although CC0 is compatible with CC BY-SA 3.0 and the whole work can be received under CC BY-SA 3.0, it would be good for people to know there are parts they …
> Add full license info for voxel textures

- compute/post_shader/post_process_grayscale.gd
- compute/post_shader/post_process_shader.gd
The compositor effect demo was attempting to free data created by a RenderingDevice using the RenderingServer. RenderingDevice RIDs are not the same as RenderingServer RIDs, and can't be freed by the RenderingServer.
> Fix VRAM leak in compositor effect demo

- misc/os_test/CSharpTest.cs
- misc/os_test/actions.gd
- misc/os_test/os_test.gd
- misc/os_test/os_test.tscn
- misc/os_test/project.godot
- Display more return values of Engine/OS methods such as system fonts, memory information and security information.
- Add headless support (the generated report is also printed to stdout).
- **Note:** Querying MIDI inputs is disabled when in headless mode to work around https://github.com/godotengine/godot/issues/52821.
- Improve theming in the generated report.
- Hide video adapter type if this information can't be queried in the current rendering method.
- Update C# script for Godot 4.x platform names.
Tested on 4.3.stable.
Full report stitched from multiple screenshots, so you can see it in all it sglory.
From VS Code's integrated terminal:
> Improve Operating System Testing demo

- 2d/dynamic_tilemap_layers/level/tile_map.gd
- 2d/dynamic_tilemap_layers/project.godot
- 2d/dynamic_tilemap_layers/world.tscn
- 2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd
- 2d/finite_state_machine/state_machine/state.gd
- 2d/isometric/player/goblin.gd
- 2d/physics_tests/tests/functional/test_one_way_collision.gd
- 2d/role_playing_game/combat/combat.gd
- 2d/role_playing_game/combat/turn_queue.gd
- 2d/role_playing_game/project.godot
- 2d/role_playing_game/theme/fonts/montserrat_extra_bold.otf.import
- 3d/squash_the_creeps/Main.gd
- audio/midi_piano/piano.gd
- audio/midi_piano/project.godot
- gui/gd_paint/paint_control.gd
- misc/2.5d/addons/node25d/.broken-gdscripts/Basis25D.gd
- misc/2.5d/addons/node25d/y_sort_25d.gd
- misc/2.5d/assets/player/player_sprite.gd
- misc/joypads/project.godot
- misc/joypads/remap/remap_wizard.gd
- networking/multiplayer_bomber/bomb.gd
- networking/multiplayer_bomber/montserrat.otf.import
- networking/multiplayer_bomber/project.godot
- xr/openxr_composition_layers/main.gd
* Replace `not X is Y` with `X is not Y`.
* This is supported since 4.3, so `project.godot` and `*.import` files for such projects have also been updated.
* Replace `# warning-ignore:X` with `@warning_ignore("X")` and remove unnecessary warning ignores.
* Convert comment keywords such as `NOTE` and `BUG` to uppercase (they are highlighted in the editor).
> Update some GDScript files

- .github/dist/footer.html
- .github/dist/header.html
- .github/workflows/export_web.yml
These demos could work if they are redesigned to account for WebXR's limitations when running on the web platform.
> Disable non-functional XR demos in web exports

- viewport/gui_in_3d/gui_panel_3d.tscn
- viewport/gui_in_3d/project.godot
- Follow-up to https://github.com/godotengine/godot-demo-projects/pull/1139.
___
- Increase physics ticks per second to 120, so that UI interactions feel smoother and have lower input lag. This happens since input is governed by the physics tick due to the use of physics picking.
- Add a placeholder to the LineEdit and select a default option in the OptionButton.
https://github.com/user-attachments/assets/1a68a9ed-c1a7-45b9-a2d4-4be7ff376f20
> Improve GUI in 3D demo

- viewport/gui_in_3d/gui_panel_3d.tscn
Make it more obvious to newcomers how this demo works so they can replicate it in their projects.
Change the text to point to how this is working.
Add Editor Descriptions to make it clearer how this is setup.
> Explain how to setup gui_in_3d

- networking/websocket_chat/websocket/WebSocketServer.gd
Seem to have been mistakenly added in 9a0c857131b8561257d3c289a0b76a611c10dbcc
> Fix typo in WebSocketServer class name

- mono/android_iap/project.godot
- This closes https://github.com/godotengine/godot-demo-projects/issues/1158.
The demo is still not ported to 4.x, but at least it should no longer display an error when you scan all demos in the project manager.
> Fix invalid icon reference in C# Android IAP demo

- networking/webrtc_signaling/client/ws_webrtc_client.gd
JSON.parse_string() parses all numbers as floats, even if there are no decimals. `str(JSON.parse_string('{"type": 3}').asdf)` would result in `"3.0"`, which is not a valid int. Because of this the demo is not working
> remove broken int type check in webrtc

- 2d/physics_tests/tests/functional/test_joints.gd
- 3d/physics_tests/tests/functional/test_joints.gd
The joint tests found in `3d/physics_tests/test/functional/test_joints.gd` are currently behaving a bit strange when you use Jolt Physics as the 3D physics engine, while having all the test options set to their default value:
https://github.com/user-attachments/assets/e48855c1-60dc-4b45-b69f-4502b2439ab7
The reason for this seems to be related to the fact that the upper body (`parent_body`) in this test is by default set to use `freeze = true`, which by default uses `freeze_mode = RigidBody3D.FREEZE_MODE_STATIC`. This effectively turns the body into a `StaticBody3D`, which as the name suggests isn't really meant to be moved, and thus have no linear or angular velocities associated with it, which will cause problems when connected to joints, as solving for the underlying joint constraints …
> Change physics joint tests to freeze bodies as kinematic

- 2d/physics_tests/tests/functional/test_character.gd
- compute/post_shader/post_process_grayscale.gd
- compute/post_shader/post_process_shader.gd
- xr/openxr_hand_tracking_demo/pickup/pickup_able_body.gd
- xr/openxr_hand_tracking_demo/pickup/pickup_handler.gd
This also reorders declarations in other projects to follow the [GDScript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html).
> Fix incorrect `class_name` declaration in 2D physics tests demo

- 3d/voxel/world/terrain_generator.gd
This adds 2 layers of dirt below the grass layer and a layer of indestructible bedrock below it so you can't fall off the world.
> Improve flat terrain generation in the Voxel demo

- 3d/voxel/menu/debug.gd
- 3d/voxel/player/player.gd
- 3d/voxel/player/player.tscn
- 3d/voxel/world/world.tscn
- Allow placing/breaking blocks when further away (up to 5 blocks instead of 4).
- Add a background to the debug display to improve readability on bright backgrounds.
- Simplify coordinate display using the `%v` placeholder available in 4.3 onwards.
> Add block placement preview to Voxel demo, improve debug display

- 3d/sprites/shaders/paper_emission.gdshader
- 3d/sprites/shaders/paper_material.gdshader
- 3d/sprites/shaders/paper_rainbow.gdshader
The normal was not calculated correctly
This is for the bug fix of the merged PR for #1191 
Before: 
After:
> Fix Sprite3D shader effect bug

- .github/workflows/export_web.yml
https://github.com/godotengine/godot-demo-projects/pull/1127#issuecomment-2885245893
In my fork it is skipped, or should we leave `static checks` active in forks?
> Disable GH `export_web` workflow in forks

- 2d/navigation_mesh_chunks/navmesh_chhunks_demo_2d.gd
- 2d/navigation_mesh_chunks/navmesh_chhunks_demo_2d.tscn
- 3d/navigation_mesh_chunks/navmesh_chhunks_demo_3d.gd
- 3d/navigation_mesh_chunks/navmesh_chhunks_demo_3d.tscn
Updates NavigationChunk demos for Godot 4.4 that has the newer `get_bounds()` function and new NavigationAgent no post-processing option.
> Update NavigationChunk demos

- networking/webrtc_signaling/server/ws_webrtc_server.gd
The _parse_msg method type-checks parsed JSON numeric values to require integers, however JSON.parse_string always returns floats, leading to a "Parse message failed" error when running the demo.
Issue link: https://github.com/godotengine/godot/issues/103374
> Fix "Parse message failed" error in WebRTC Signaling Demo Project

- 2d/custom_drawing/meshes.gd
I've removed the comment about the `MultiMesh` crash and opened https://github.com/godotengine/godot/issues/108566.
> Simplify mesh custom drawing demo

- 2d/bullet_shower/bullets.gd
- 2d/bullet_shower/player.gd
- 2d/physics_platformer/stage.tscn
- 3d/graphics_settings/settings.gd
- 3d/ik/addons/sade/ik_fabrik.gd
- 3d/ik/fps/example_player.gd
- 3d/labels_and_texts/README.md
- 3d/sprites/README.md
- compute/texture/water_plane/water_compute.glsl
- gui/gd_paint/paint_control.gd
- gui/gd_paint/tools_panel.gd
- gui/translation/README.md
- gui/translation/translation_demo_po.tscn
- gui/translation/translations/po/translation_demo.pot
- gui/translation/translations/po/translation_demo_es.po
- gui/translation/translations/po/translation_demo_ja.po
- misc/graphics_tablet_input/graphics_tablet_input.gd
- misc/joypads/joypads.gd
- misc/window_management/README.md
- networking/webrtc_signaling/README.md
- networking/webrtc_signaling/project.godot
- networking/websocket_chat/client.gd
- plugins/addons/material_creator/material_resource.gd
- viewport/2d_in_3d/pong.gd
- viewport/dynamic_split_screen/README.md
- viewport/dynamic_split_screen/camera_controller.gd
- xr/openxr_character_centric_movement/README.md
- xr/openxr_hand_tracking_demo/README.md
- xr/openxr_origin_centric_movement/README.md
This is a set of hand picked and entered (no LLM's here) spelling fixes in only strings, comments and non-code files.
No functional changes should exist here: I avoided changing any variables or other code based spellings.
These should be non-controversial: I didn't get into yak shaving about hyphenated words or industry terms. Just the "normal words", and I tried to avoid changing anything that was just an acceptable alternate based on national origin (i.e. US vs British).
Credit to `cspell`: I used `cspell` to find these to start with, but the changes were hand picked based on being good targets and then hand-fixed to make sure they made sense in context and had no affect on code operation.
As justification: Finding a lot of spelling mistakes in comments and descriptions causes some …
> Minor spelling fixes in strings, comments and non-code files.

- compute/texture/water_plane/water_plane.gd
Fix uniform sets that were hardcoded as `0`, which seems to work with `v4.4` but has broken this demo in `v4.5`.
Still works with `v4.4.1` ✅ 
Also removed the unnecessary texture usage bits.
---
```
ERROR: Uniforms supplied for set (2):
ERROR: Set: 0 Binding: 0 Type: Image Writable: N Length: 1
ERROR: are not the same format as required by the pipeline shader. Pipeline shader requires the following bindings:
ERROR: Set: 0 Binding: 0 Type: Image Writable: N Length: 1
ERROR: Set: 1 Binding: 0 Type: Image Writable: N Length: 1
ERROR: Set: 2 Binding: 0 Type: Image Writable: Y Length: 1
```
> Fix uniform sets in "Compute Texture"

- 3d/voxel/project.godot
This avoids stuttering during world generation due to mutating compound shapes being slow in Jolt Physics.
This is especially noticeable in the Flat Grass world due to the higher number of voxels being generated.
- See https://github.com/godotengine/godot/pull/111115.
> Use GodotPhysics3D in Voxel demo to work around performance issue

- 2d/navigation_astar/character.gd
- 2d/navigation_astar/game.tscn
- 2d/navigation_astar/project.godot
Previously, the way in which the spaceship steered depended on the rendered framerate. Very low framerates (< 20) could cause the ship to steer in circles with sharp turns.
This moves ship movement to the physics step to avoid this, and enables physics interpolation for smooth motion.
I noticed this while testing https://github.com/godotengine/godot-demo-projects/pull/1208.
> Fix FPS-dependent movement in Navigation AStar demo

- gui/multiple_resolutions/main.gd
While the demo seems to work, the editor won't allow the user to jump to the docs when using Ctrl+LMB
> Fix `content_scale_*` updates: properties are in `Window` not `(Sub-)Viewport`

- README.md
@akien-mga expressed awhile ago that this list of branches would become unsustainable. Considering the lack of activity in the demo projects repo, and the increased pace of releases in the engine repo (yay!), I'm now in full agreement with that.
> Simplify list of branches in the README

- 2d/dynamic_tilemap_layers/README.md
Fixes
https://github.com/godotengine/godot-demo-projects/issues/1163#
> Update README.md - Indicate demo obsolete for godot 4.3+
