3d/kinematic_char/cubio.gd

Just think of how many Toads weren't saved because of this...

Fix bug that could prevent cubio from saving the princess

---

2d/split_screen_platformer/player.gd
2d/split_screen_platformer/player.tscn

This PR is so I can kickstart my **hacktoberfest** activity~
>In Split screen platform demo
Using export with **String/int** is more user-friendly.
Thanks ☺️

Export player index

---

networking/simple_multiplayer/gamestate.gd

Properly send newly connected dudes to old players.

Fix simple multiplayer demo for 3+ players

---

2d/split_screen_platformer/split_stage.gd
2d/split_screen_platformer/split_stage.tscn

Hi, another PR for hacktoberfest ( it's really nice to work with godot engine :blush: )
> Split screen platformer
I added a system to change split screen mode (between horizontal and vertical).
I hope this method using constants is correct.
Sample using process+animation:

Add split-screen modes (horizontal/vertical)

---

2d/hexagonal_map/troll.gd
2d/isometric/troll.gd
2d/kinematic_character/player.gd
2d/kinematic_collision/player.gd
2d/physics_platformer/coin.tscn
2d/physics_platformer/enemy.tscn
2d/physics_platformer/moving_platform.gd
2d/platformer/coin.tscn
2d/platformer/enemy.gd
2d/platformer/enemy.tscn
2d/platformer/moving_platform.gd
2d/platformer/player.gd
3d/kinematic_character/cubio.gd
3d/kinematic_character/follow_camera.gd
3d/platformer/follow_camera.gd
3d/platformer/player.gd
misc/joypads/joypads.gd
misc/window_management/control.gd
misc/window_management/observer/observer.gd
networking/simple_multiplayer/player.gd

The following PR renamed fixed_process to physics_process within the Godot engine: https://github.com/godotengine/godot/pull/11659
This PR updates the demo projects to use this new naming

Fixes for rename from fixed to physics

---

misc/window_management/observer/observer.gd
misc/window_management/window_management.tscn

When anchors set to 1, the margins should have been ported to negative numbers. Also renamed the obsolete move function.

fixed anchors and renamed move function for window management demo

---

2d/space_shooter/engine.cfg
2d/space_shooter/ship.gd

- renamed the project
- made the ship can't do shooting when killed.

[2.1] 2D/space_shooter: Some tweaks

---

2d/platformer/bullet.png.import
2d/platformer/bullet.tscn
2d/platformer/coin.png.import
2d/platformer/enemy.png.import
2d/platformer/enemy.tscn
2d/platformer/icon.png.import
2d/platformer/moving_platform.png.import
2d/platformer/music.ogg.import
2d/platformer/one_way_platform.png.import
2d/platformer/osb_fire.png.import
2d/platformer/osb_jump.png.import
2d/platformer/osb_left.png.import
2d/platformer/osb_right.png.import
2d/platformer/robot_demo.png.import
2d/platformer/scroll_bg_cloud_1.png.import
2d/platformer/scroll_bg_cloud_2.png.import
2d/platformer/scroll_bg_cloud_3.png.import
2d/platformer/scroll_bg_fg_1.png.import
2d/platformer/scroll_bg_fg_2.png.import
2d/platformer/scroll_bg_sky.png.import
2d/platformer/stage.tscn
2d/platformer/tiles_demo.png.import

- added background music
- should be able to fix https://github.com/godotengine/godot-demo-projects/issues/58

2D/Platformer: Several Enhancement added

---

mono/monkey_pong/Ball.cs
mono/monkey_pong/CeilingFloor.cs
mono/monkey_pong/Paddle.cs
mono/monkey_pong/Wall.cs

- Use pattern matching instead of check-and-cast.
- Rename constants to fit the usual c# code-style.

Code enhancements for the mono pong demo.

---

2d/light2d_as_mask/project.godot
2d/platformer/project.godot
misc/sensors/project.godot
viewport/2d_in_3d/project.godot
viewport/3d_in_2d/project.godot
viewport/gui_in_3d/project.godot
viewport/screen_capture/project.godot

This also makes the name of the 2D platformer demo more descriptive.

Fix project names to use consistent casing

---

README.md

This adds a notice about engine version compatibility, possibly fixing issues like https://github.com/godotengine/godot-demo-projects/issues/229.

Reorganize README and add a notice about engine version compatibility

---

misc/android_iap/iap.gd
misc/android_iap/iap_demo.gd
misc/android_iap/main.tscn

This PR updates some changes between 2.x and 3.x

Update description for setting up android iap

---

misc/android_iap/iap.gd

Fix https://github.com/godotengine/godot/issues/22909

Fix a typo in GodotPayment(s)

---

2d/finite_state_machine/player/weapon/sword.gd

Not sure if this is wanted, but this pull request fixes the FSM demo
I was not able to run this demo using the latest Godot changes.

Fixed Finite State Machine error with enums

---

2d/navigation/level.tscn
2d/navigation/navigation.gd

Fix navigation demo not reaching the final point

---

2d/physics_platformer/background/Seesaw.tscn

Seesaw did stand up in 2d Demo - Physics Platformer.
Add a pilar as static body and reasign PinJoin2D nodes

Fix seesaw falling plank from 2d demo

---

2d/screen_space_shaders/screen_shaders.tscn
2d/screen_space_shaders/shaders/BCS.shader
2d/screen_space_shaders/shaders/blur.shader
2d/screen_space_shaders/shaders/contrasted.shader
2d/screen_space_shaders/shaders/mirage.shader
2d/screen_space_shaders/shaders/negative.shader
2d/screen_space_shaders/shaders/normalized.shader
2d/screen_space_shaders/shaders/old_film.shader
2d/screen_space_shaders/shaders/pixelize.shader
2d/screen_space_shaders/shaders/sepia.shader
2d/screen_space_shaders/shaders/vignette.shader
2d/screen_space_shaders/shaders/whirl.shader
2d/sprite_shaders/shaders/aura.shader
2d/sprite_shaders/shaders/blur.shader
2d/sprite_shaders/shaders/dissintegrate.shader
2d/sprite_shaders/shaders/dropshadow.shader
2d/sprite_shaders/shaders/fatty.shader
2d/sprite_shaders/shaders/glow.shader
2d/sprite_shaders/shaders/offsetshadow.shader
2d/sprite_shaders/shaders/outline.shader
2d/sprite_shaders/shaders/silouette.shader
2d/sprite_shaders/sprite_shaders.tscn

I was looking at the shader examples to explain them to a friend and we had some dificulty navigating and comparing the different shaders in the examples, and having each shader in it's individual file instead of internal to the scene helped a lot.

Extract shader code from 2D shader demos

---

viewport/2d_in_3d/2D_in_3D.gd
viewport/2d_in_3d/2D_in_3D.tscn
viewport/2d_in_3d/ball.png.import
viewport/2d_in_3d/default_env.tres
viewport/2d_in_3d/icon.png.import
viewport/2d_in_3d/left_pallete.png.import
viewport/2d_in_3d/pong.gd
viewport/2d_in_3d/right_pallete.png.import
viewport/2d_in_3d/separator.png.import

Conform to style guide, make positions exact, fix viewport quad. Closes #292.

Update 2D in 3D demo to Godot 3.1.2

---

2d/finite_state_machine/player/Player.tscn
2d/gd_paint/Paint_root.tscn
viewport/dynamic_split_screen/SplitScreen.tscn
viewport/gui_in_3d/gui_in_3d.tscn
viewport/gui_in_3d/view_gui.tscn

To easily do this manually, add this alias:
alias tscnnoeditor="find . -name '*.tscn' -exec sed -i '/^editor\//d' {} \;" # Remove "editor/display_folded"

Clean up editor/display_folded

---

2d/finite_state_machine/Demo.tscn
2d/finite_state_machine/debug/ControlsPanel.tscn
2d/finite_state_machine/debug/states_stack_displayer.gd
2d/finite_state_machine/player/Player.tscn
2d/finite_state_machine/player/bullet/Bullet.tscn
2d/finite_state_machine/player/bullet/bullet.gd
2d/finite_state_machine/player/bullet/bullet_spawner.gd
2d/finite_state_machine/player/player_controller.gd
2d/finite_state_machine/player/player_state_machine.gd
2d/finite_state_machine/player/states/combat/attack.gd
2d/finite_state_machine/player/states/combat/stagger.gd
2d/finite_state_machine/player/states/debug/state_name_displayer.gd
2d/finite_state_machine/player/states/die.gd
2d/finite_state_machine/player/states/motion/in_air/jump.gd
2d/finite_state_machine/player/states/motion/motion.gd
2d/finite_state_machine/player/states/motion/on_ground/idle.gd
2d/finite_state_machine/player/states/motion/on_ground/move.gd
2d/finite_state_machine/player/states/motion/on_ground/on_ground.gd
2d/finite_state_machine/player/weapon/Sword.tscn
2d/finite_state_machine/player/weapon/sword.gd
2d/finite_state_machine/player/weapon/weapon_pivot.gd
2d/finite_state_machine/project.godot
2d/finite_state_machine/state_machine/state.gd
2d/finite_state_machine/state_machine/state_machine.gd
3d/platformer/stage.tscn

As usual, update, test, and conform to style guide. Fix all warnings, closes #305.

Update Finite State Machine demo to Godot 3.1.2

---

2d/particles/particles.tscn
2d/physics_platformer/Stage.tscn
2d/physics_platformer/Stage2.tscn
2d/physics_platformer/TilesetEdit.tscn
2d/physics_platformer/background/ParallaxBg.tscn
2d/physics_platformer/coin/Coin.tscn
2d/physics_platformer/coin/coin.gd
2d/physics_platformer/enemy/Enemy.tscn
2d/physics_platformer/enemy/enemy.gd
2d/physics_platformer/platform/MovingPlatform.tscn
2d/physics_platformer/platform/OneWayPlatform.tscn
2d/physics_platformer/platform/moving_platform.gd
2d/physics_platformer/player/Bullet.tscn
2d/physics_platformer/player/Player.tscn
2d/physics_platformer/player/bullet.gd
2d/physics_platformer/player/player.gd
2d/physics_platformer/project.godot

As usual, update, test, and conform to style guide, fix all warnings, etc. Use enum for State, and use TAU instead of PI * 2. Also add support for using WASD and using controllers.
Notably, add an AudioStreamPlayer to play the music, which was in the project but didn't ever play.

Update 2D physics platformer

---

LICENSE.md
README.md

I'm making identical PRs for each branch.

[2.1] Update README and LICENSE

---

LICENSE.md
README.md

I'm making identical PRs for each branch.

[3.0] Update README and LICENSE

---

README.md

This may be helpful to newcomers; see #423.

Add instructions on importing all projects at once in the README

---

misc/joypads/joypad_diagram.tscn
misc/joypads/joypads.gd
misc/joypads/joypads.tscn

Conform to style guides, rework UI to use containers, and make some visual changes.
Before:
After:

Refactor the Joypads demo

---

2d/finite_state_machine/state_machine/state_machine.gd

Fix incorrect comment in hierarchical FSM demo script

---

2d/navigation_astar/character.gd
2d/navigation_astar/pathfind_astar.gd
3d/kinematic_character/cubio.gd
3d/kinematic_character/project.godot

Navigation Astar:
* Improve readability of some of the code.
* Make more things private by prefixing them with an underscore.
* Fix confusing name of `_get_path` since it's not supposed to be private and only had the underscore to avoid conflicting with `get_path`. It's now `get_astar_path`.
* Change the character to `extends Node2D`.
Kinematic Character 3D:
* Add controller support.
* Use gravity from project settings.
* Use full words for variables and add comments.

Some changes to Astar and Kinematic Character 3D

---

loading/multiple_threads_loading/icon.png.import
loading/multiple_threads_loading/images/.gitignore
loading/multiple_threads_loading/preload.gd
loading/multiple_threads_loading/preload.tscn

Amending #425 with some minor changes.

Style tweaks and add import files to multiple threads loading demo

---

2d/dodge_the_creeps/Main.gd
2d/dodge_the_creeps/Mob.gd
mono/dodge_the_creeps/Main.cs
mono/dodge_the_creeps/Mob.cs

This is for #454.
A [small part from the tutorial](https://docs.godotengine.org/en/3.2/getting_started/step_by_step/your_first_game.html#removing-old-creeps) for the dodge_the_creeps demo was missing in the project here.

Updated the dodge_the_creeps demo to include the "Removing the creeps" part in the tutorial.

---

2d/physics_platformer/README.md
2d/platformer/README.md

The music is "Pompy" by Hubert Lamontagne (madbr) https://soundcloud.com/madbr/pompy

Add credits for the music used in the 2D platformer demos

---

.gitignore

Now synced with GitHub's Godot.gitignore plus the bottom section.
https://github.com/github/gitignore/blob/master/Godot.gitignore

Add translation ignore

---

.gitignore
2d/screen_space_shaders/README.md
2d/screen_space_shaders/project.godot

Convert the Screen Space Shaders demo back to GLES 3

---

2d/dodge_the_creeps/README.md

It originally said that "Abstract Platformer" was copyright kenny.nl.
This is not true. "Abstract Platformer" was dedicated to the public
domain using CC0. "When CC0 is applied to a work, copyright no longer
applies to the work in most jurisdictions around the world." (Source:
https://creativecommons.org/faq/#how-do-cc-licenses-operate)
It also said that "Abstract Platformer" was created in the years
2010-2020. While the "Abstract Platformer" webpage
(https://www.kenney.nl/assets/abstract-platformer) does say "Copyright ©
2010 - 2020", I believe that that's a copyright notice for the website
itself, not the asset pack. I'm not sure when Kenney started working on
"Abstract Platformer", but I'm confident that it was published in 2016
because:
* All of the files in the ZIP archive are dated …

Correct Dodge the Creeps' copyright info

---

misc/android_iap/iap_demo.gd

Thanks to @HEAVYPOLY for testing

Fix small mistakes with new Android IAP API

---

misc/android_iap/iap_demo.gd

This PR reflects the recent changes we made to the `GodotGooglePlayBilling` (ex. `GodotPayment`) Android plugin. See https://github.com/godotengine/godot-google-play-billing/pull/1

Update Android IAP demo to reflect recent changes

---

2d/platformer/src/Actors/Player.gd

This feels more smooth while still giving a sense of control to the player.

Progressively interrupt the jump in the 2D platformer demo

---

.github/workflows/static_checks.yml
2d/gd_paint/paint_control.gd
file_format.sh
mono/2.5d/addons/node25d-cs/Node25D.cs
mono/2.5d/addons/node25d-cs/ShadowMath25D.cs

Tweak naming, add auto-` == true` removal, add line removal around braces from [PR 38812](https://github.com/godotengine/godot/pull/38812). See also [PR 40335](https://github.com/godotengine/godot/pull/40335).

Tweak CI to more closely match the main repo

---

gui/rich_text_bbcode/rich_text_bbcode.gd
gui/rich_text_bbcode/rich_text_bbcode.tscn
gui/translation/translation_demo.gd
gui/translation/translation_demo.tscn

A Panel without a panel is the same as a Control, so replace with Control nodes.

Remove Panel nodes that don't have panels

---

3d/navmesh/navmesh.gd

Hi,
I found the previous code that implemented the navmesh path following to be quite complex and a little difficult to follow.
I've tried to simplify it as much as I can and document what does what, and any considerations that went into it.
As far as I can tell it behaves identically to the previous code, I appreciate any second opinions though!
Please let me know if this is ok / if I've added too many comments, or any other recommendations.
I'm hoping this will be more approachable for newcomers to Godot.
Thanks,
Jak

Re-write the navigation path-following code to be easier to read + add comments

---

2d/dodge_the_creeps/Main.gd
2d/dodge_the_creeps/Main.tscn
2d/dodge_the_creeps/Player.gd
mono/dodge_the_creeps/Main.cs
mono/dodge_the_creeps/Main.tscn
mono/dodge_the_creeps/Player.cs

I will update this PR if I need to make any further changes during the review of https://github.com/godotengine/godot-docs/pull/4208

Change Dodge the Creeps to be more consistent with the docs

---

gui/theming_override/README.md
mono/android_iap/README.md
mono/multiplayer_pong/README.md
networking/multiplayer_pong/README.md

Also change the wording of the Pong Multiplayer demo to match Pong Multiplayer with C#.

Add links to the Asset Library after release 3.2-5bd2bbf

---

3d/physics_tests/project.godot
3d/physics_tests/test.gd
3d/physics_tests/tests.gd
3d/physics_tests/tests/functional/test_pyramid.gd
3d/physics_tests/tests/functional/test_pyramid.tscn
3d/physics_tests/tests/functional/test_raycasting.gd
3d/physics_tests/tests/functional/test_raycasting.tscn
3d/physics_tests/tests/functional/test_stack.gd
3d/physics_tests/tests/functional/test_stack.tscn
3d/physics_tests/tests/performance/test_perf_broadphase.gd
3d/physics_tests/tests/performance/test_perf_broadphase.tscn
3d/physics_tests/tests/performance/test_perf_contacts.gd
3d/physics_tests/tests/static_scene.tscn
3d/physics_tests/tests/static_scene_plane.tscn
3d/physics_tests/utils/container_log.gd

* Add Functional Test / Stack & Pyramid
For testing stack stability.
* Add Functional Test / Raycasts
Visually test raycast on different shapes.
* Fix leaks on exit
Some Nodes are copied and removed from the scene to be used as templates,
they need to be freed manually on exit.
* Fix Performance Test / Contacts
Positions adjusted, some shape types were not created at the center.

Fixes and adjustments in 3D physics tests

---

2d/physics_tests/test.gd
2d/physics_tests/tests.gd
2d/physics_tests/tests/functional/test_collision_pairs.gd
2d/physics_tests/tests/functional/test_collision_pairs.tscn
2d/physics_tests/tests/functional/test_raycasting.gd
2d/physics_tests/tests/functional/test_shapes.tscn
2d/physics_tests/tests/performance/test_perf_contacts.tscn
2d/physics_tests/utils/option_menu.gd
3d/physics_tests/test.gd
3d/physics_tests/tests.gd
3d/physics_tests/tests/functional/test_collision_pairs.gd
3d/physics_tests/tests/functional/test_collision_pairs.tscn
3d/physics_tests/tests/functional/test_raycasting.gd
3d/physics_tests/tests/performance/test_perf_contacts.gd
3d/physics_tests/utils/option_menu.gd

Functional test used for checking/debugging different collision cases for all possible pairs of shape types.
Minor changes in a few other tests to keep things consistent.
Note: In 3D, Bullet and GodotPhysics currently don't agree on whether contact points returned by `PhysicsDirectSpaceState::collide_shape` should be in local space or world space. I'm assuming world space to be consistent with 2D, but with Bullet they are not drawn in the correct location because of this discrepancy.

Add collision pairs test to 2D/3D physics tests

---

.github/CODEOWNERS

As suggested in https://github.com/godotengine/godot-demo-projects/pull/561#pullrequestreview-555917317

Add PouleyKetchoupp to owners for physics tests

---

2d/platformer/assets/theme/user_interface.tres
2d/platformer/src/Actors/Player.gd
2d/platformer/src/Objects/Coin.gd
2d/platformer/src/Objects/Coin.tscn
2d/platformer/src/UserInterface/CoinsCounter.gd
2d/platformer/src/UserInterface/CoinsCounter.tscn
2d/platformer/src/UserInterface/PauseMenu.gd
2d/platformer/src/UserInterface/PauseMenu.tscn

This is a subset of #548, it's just the Platformer 2D changes, but vastly simplified and with many bugs fixed. I marked @Mr-K-GameDev  as the author since most of the additions are still his, though I trimmed those additions down.

Add a coin counter and pause menu fading to Platformer 2D

---

2d/physics_tests/test.gd
2d/physics_tests/tests.gd
2d/physics_tests/tests/functional/test_collision_pairs.gd
2d/physics_tests/tests/functional/test_joints.gd
2d/physics_tests/tests/functional/test_joints.tscn
2d/physics_tests/tests/functional/test_pyramid.gd
2d/physics_tests/tests/functional/test_stack.gd
2d/physics_tests/utils/rigidbody_pick.gd
3d/physics_tests/test.gd
3d/physics_tests/tests.gd
3d/physics_tests/tests/functional/test_collision_pairs.gd
3d/physics_tests/tests/functional/test_joints.gd
3d/physics_tests/tests/functional/test_joints.tscn
3d/physics_tests/tests/functional/test_pyramid.gd
3d/physics_tests/tests/functional/test_stack.gd
3d/physics_tests/utils/camera_orbit.gd
3d/physics_tests/utils/rigidbody_pick.gd

Functional test used for checking/debugging all different joint types.
Also added the possibility to pick and move 2D and 3D bodies to some tests.

Add joints test to 2D/3D physics tests

---

2d/physics_tests/main.tscn
2d/physics_tests/project.godot
2d/physics_tests/tests/functional/test_collision_pairs.tscn
2d/physics_tests/tests/functional/test_one_way_collision.tscn
2d/physics_tests/tests/functional/test_raycasting.tscn
2d/physics_tests/tests/test_options.tscn
2d/physics_tests/utils/label_pause.gd
2d/physics_tests/utils/system.gd
3d/physics_tests/main.tscn
3d/physics_tests/project.godot
3d/physics_tests/tests/functional/test_collision_pairs.tscn
3d/physics_tests/tests/functional/test_raycasting.tscn
3d/physics_tests/tests/test_options.tscn
3d/physics_tests/utils/label_pause.gd
3d/physics_tests/utils/system.gd

New controls for all tests:
P to toggle pause on/off
Affects the running tests but not menus.

Support for pause in 2D/3D physics tests

---

3d/truck_town/car_base.tscn
3d/truck_town/car_select.tscn
3d/truck_town/project.godot
3d/truck_town/spedometer.gd
3d/truck_town/tow_truck.tscn
3d/truck_town/town_scene.tscn
3d/truck_town/trailer_truck.tscn
3d/truck_town/vehicle.gd

Follow-up to #581. Engine force is now dynamic based on the speed, and the gravity is back to Earth gravity. I also added a spedometer because I think it's nice to know how fast your vehicle is going (click to change units).

Use a higher engine force when slow and add a spedometer in Truck Town

---

2d/physics_tests/main.tscn
2d/physics_tests/tests.gd
2d/physics_tests/tests/functional/test_character.gd
2d/physics_tests/tests/functional/test_character_pixels.gd
2d/physics_tests/tests/functional/test_character_pixels.tscn
2d/physics_tests/tests/functional/test_character_slopes.tscn
2d/physics_tests/tests/functional/test_character_tilemap.gd
2d/physics_tests/tests/functional/test_character_tilemap.tscn
2d/physics_tests/tests/functional/test_collision_pairs.gd
2d/physics_tests/tests/functional/test_joints.gd
2d/physics_tests/tests/functional/test_one_way_collision.gd
2d/physics_tests/tests/functional/test_one_way_collision.tscn
2d/physics_tests/tests/performance/test_perf_contacts.gd
2d/physics_tests/utils/kinematicbody_controller.gd
2d/physics_tests/utils/rigidbody_controller.gd
2d/physics_tests/utils/scroll_log.gd

Added new test for 2D character controller:
Character - Pixels
Functional test for pixel art related issues around KinematicBody and RigidBody character controllers.
Adjusted existing tests and added more test cases to cover most use cases from recent fixed issues and regressions for KinematicBody.
Added a more automated way to run all tests with checks to see which ones failed in character controller tests.
Also fixed some minor issues with the log scrollbar.

Updated 2D character controller physics tests

---

.github/dist/header.html
.github/workflows/export_html5.yml
README.md

Preview here: https://aaronfranke.github.io/godot-demo-projects/

Link to the web export in the README and format names nicer

---

2d/physics_tests/test.gd
2d/physics_tests/tests/functional/test_character.gd
2d/physics_tests/tests/functional/test_character_pixels.gd
2d/physics_tests/tests/functional/test_character_tilemap.gd
2d/physics_tests/tests/functional/test_one_way_collision.gd

Allows canceling running test cases (including all tests cases) properly and without error.

Physics test cases, cancel previous running test properly

---

.github/CODEOWNERS
2d/bullet_shower/README.md
2d/physics_tests/README.md
3d/waypoints/README.md
gui/control_gallery/README.md
loading/serialization/README.md

Also expand the CODEOWNERS file

Add links to the Asset Library after release 3.2-5c154da

---

2d/bullet_shower/bullets.gd

Move physics processing code from `_process()` to `_physics_process()`.

Small improvement for Bullet Shower Demo

---

2d/finite_state_machine/player/states/motion/in_air/jump.gd
2d/finite_state_machine/player/states/motion/on_ground/move.gd
2d/platformer/src/Actors/Enemy.gd
2d/platformer/src/Actors/Player.gd
2d/platformer/src/Level/Music.gd
2d/pong/logic/paddle.gd
3d/voxel/menu/ingame/pause_menu.gd
misc/joypads/remap/remap_wizard.gd
networking/websocket_chat/utils.gd

This should be easier to read, especially for people who are new to Godot.
Also, I decreased the Platformer 2D volume from -4 to -14 (about half perceived volume, but actually about a third of the amplitude, or one tenth of the sound wave's power in watts).

Use fewer ternary operators and decrease volume of Platformer 2D

---

2d/physics_tests/test.gd
2d/physics_tests/tests/functional/test_collision_pairs.gd
2d/physics_tests/tests/functional/test_joints.gd
2d/physics_tests/tests/functional/test_pyramid.gd
2d/physics_tests/tests/functional/test_stack.gd
2d/physics_tests/tests/performance/test_perf_broadphase.gd
2d/physics_tests/tests/performance/test_perf_contacts.gd
2d/physics_tests/tests/performance/test_perf_contacts.tscn
2d/physics_tests/utils/option_menu.gd
3d/physics_tests/test.gd
3d/physics_tests/tests/functional/test_collision_pairs.gd
3d/physics_tests/tests/functional/test_joints.gd
3d/physics_tests/tests/performance/test_perf_broadphase.gd
3d/physics_tests/tests/performance/test_perf_contacts.gd
3d/physics_tests/tests/performance/test_perf_contacts.tscn
3d/physics_tests/tests/performance/test_perf_contacts_extended.tscn
3d/physics_tests/utils/option_menu.gd

* Added proper logs for physics ticks
* Optimizations and cleaning in scripts
* In 3D, use `PlaneShape` instead of `ConcavePolygonShape` for walls because it contains the shapes better

Updated 2d/3d physics contact performance tests

---

viewport/3d_in_2d/robot_3d.gd
viewport/3d_in_2d/robot_3d.tscn

Remove the skeleton/armature and remove the physics stuff, because it's not needed for this demo.

Simplify 3D robot in the 3D in 2D demo

---

3d/physics_tests/project.godot
3d/physics_tests/tests.gd
3d/physics_tests/tests/functional/test_moving_platform.gd
3d/physics_tests/tests/functional/test_moving_platform.tscn
3d/physics_tests/utils/kinematicbody_physics.gd

Manually and visually testable variations of the KinematicBody platform with KinematicBody & RigidBody characters on it.
The test options menu has visually persistent toggles - doesn't hide options between active character body types.

3D physics tests - Moving platform

---

2d/finite_state_machine/debug/states_stack_displayer.gd
2d/finite_state_machine/player/states/debug/state_name_displayer.gd
2d/navigation_astar/character.gd
2d/physics_tests/tests/functional/test_collision_pairs.gd
2d/physics_tests/tests/functional/test_raycasting.gd
2d/physics_tests/tests/performance/test_perf_contacts.gd
2d/pong/logic/paddle.gd
2d/pong/project.godot
2d/screen_space_shaders/screen_shaders.gd
3d/material_testers/tester.gd
3d/physics_tests/tests/functional/test_collision_pairs.gd
3d/physics_tests/tests/performance/test_perf_contacts.gd
3d/platformer/player/follow_camera.gd
3d/platformer/player/player.gd
3d/voxel/menu/debug.gd
3d/voxel/menu/ingame/pause_menu.gd
audio/bpm_sync/bpm_sync.gd
misc/2.5d/addons/node25d/main_screen/gizmo_25d.gd
misc/2.5d/addons/node25d/main_screen/viewport_25d.gd
misc/2.5d/addons/node25d/node_25d.gd
misc/2.5d/assets/player/player_math_25d.gd
misc/2.5d/assets/player/player_sprite.gd
misc/2.5d/assets/ui/control_hints.gd
misc/window_management/control.gd
misc/window_management/observer/observer.gd
mobile/android_iap/iap_demo.gd
mobile/multitouch_cubes/GestureArea.gd
mono/2.5d/addons/node25d-cs/main_screen/viewport_25d.gd
mono/2.5d/assets/ui/control_hints.gd
networking/multiplayer_bomber/player.gd

`not` is the preferred GDScript style according to the style guide.
Also, I added an explicit cast to String around name. This helps with 4.0 compatibility but still works fine in 3.x.

Use "not" instead of the exclamation mark in GDScript files

---

2d/platformer/src/Actors/Player.gd

Small PR to utilize the jump sound effect node already present in the Player node tree

Use the Jump sound already present in the Platformer 2D demo

---

2d/finite_state_machine/Demo.tscn
2d/finite_state_machine/player/Player.tscn
2d/finite_state_machine/player/bullet/bullet_spawner.gd

The bullets were marked as top level nodes, but their position was never assigned.
Also, I removed a one-node scene in favor of just placing that node directly in the demo scene.

Fix bullets in the Finite State Machine demo

---

2d/dodge_the_creeps/Main.gd
2d/dodge_the_creeps/Mob.gd
2d/dodge_the_creeps/README.md
2d/pong/README.md
2d/pong/logic/ball.gd
3d/voxel/settings.gd
mono/dodge_the_creeps/Main.cs
mono/dodge_the_creeps/Mob.cs
mono/dodge_the_creeps/README.md
mono/pong/README.md
networking/webrtc_minimal/chat.gd
networking/webrtc_minimal/main.gd

These tweaks were prompted by the recent creations of the GDNative C++ versions of these demos.

Minor tweaks to Pong and Dodge the Creeps

---

misc/opensimplexnoise/OpenSimplexNoise_Viewer.gd
misc/opensimplexnoise/OpenSimplexNoise_Viewer.tscn

- Saving everything to an image causes lag spikes
- Clean up GUI
- Fix min/max/step of spin boxes
- Add random seed button

Simplify and improve OpenSimplexNoise viewer

---

audio/mic_record/MicRecord.gd

Fix stall when playing recorded audio

---

2d/platformer/src/Actors/Gun.gd

Updating 2D Platformer demo to restart cooldown timer when once the gun has fired

2d platformer gun cooldown fix

---

networking/websocket_minimal/Main.tscn
networking/websocket_minimal/client.gd
networking/websocket_minimal/project.godot
networking/websocket_minimal/server.gd

Update the networking/websocket-minimal project to use gdscript 2.0.

feat: update websocket-minimal to gdscript2.0

---

2d/instancing/README.md
2d/instancing/bowling_ball.png.import
2d/instancing/icon.png.import
2d/instancing/project.godot
2d/instancing/scene_instancing.tscn

Everything works! Project settings are updated to Godot 4 new standards.
Another task which can be checked of #697.

Tested and fixed Scene Instancing Demo for 4.0-dev

---

2d/bullet_shower/README.md
2d/bullet_shower/bullet.png.import
2d/bullet_shower/bullets.gd
2d/bullet_shower/face_happy.png.import
2d/bullet_shower/face_sad.png.import
2d/bullet_shower/icon.png.import
2d/bullet_shower/player.gd
2d/bullet_shower/project.godot
2d/bullet_shower/shower.tscn

Fixed some issues of things which changed in Godot 4 and I also tried replicating this issue #599 but I guess that is not longer an issue in Godot 4.0? Tested and fixed everything on Godot 4.0 alpha-5.

Update for Bullet Shower to 4.0-dev

---

viewport/gui_in_3d/gui_panel_3d.tscn

GUI in 3D: Always process GUI even when the scene tree is paused

---

gui/translation/text.csv
gui/translation/translation_demo.gd
gui/translation/translation_demo.tscn

Fixes #647
I added an example of how you can handle translations on runtime.
Small fix

Added run-time translation example for Translation Demo 4.0-dev

---

2d/screen_space_shaders/README.md
2d/screen_space_shaders/art/burano.jpg.import
2d/screen_space_shaders/art/filmgrain.png.import
2d/screen_space_shaders/art/forest.jpg.import
2d/screen_space_shaders/art/mountains.jpg.import
2d/screen_space_shaders/art/platformer.jpg.import
2d/screen_space_shaders/art/vignette.png.import
2d/screen_space_shaders/art/white.png.import
2d/screen_space_shaders/icon.png.import
2d/screen_space_shaders/project.godot
2d/screen_space_shaders/screen_shaders.tscn

Screen Space Shader Update to 4.0

---

gui/pseudolocalization/Pseudolocalization.gd
gui/pseudolocalization/Pseudolocalization.tscn
gui/pseudolocalization/README.md
gui/pseudolocalization/icon.png.import
gui/pseudolocalization/project.godot

There were some UI issues + pressed became button_pressed.
Also updated to Vulkan Mobile and changed the README to Vulkan Mobile.
Part of #697.

Fixed some issues in Pseudo localization Demo 4.0-dev

---

README.md

And add link to `4.0-dev` branch to `master` upstream.

Clarify that `master` here tracks `3.x` upstream

---

networking/multiplayer_bomber/brickfloor.png.import
networking/multiplayer_bomber/charwalk.png.import
networking/multiplayer_bomber/explosion.png.import
networking/multiplayer_bomber/icon.png.import
networking/multiplayer_bomber/lobby.tscn
networking/multiplayer_bomber/montserrat.otf.import
networking/multiplayer_bomber/player.tscn
networking/multiplayer_bomber/project.godot
networking/multiplayer_bomber/rock.tscn
networking/multiplayer_bomber/rock_bit.png.import
networking/multiplayer_bomber/score.gd
networking/multiplayer_bomber/tile_scene.tscn
networking/multiplayer_bomber/tileset.tres
networking/multiplayer_bomber/world.tscn

This should have no *functional* changes. The most interesting differences are related to `FileData` becoming `FontFile`. A lot of the .tscn/.import changes are just from opening in the editor and saving.

Update the multiplayer_bomber demo to work with Godot 4.0-beta3

---

README.md

change (currently 4.0-alpha) to (currently 4.0-beta).

Update 4.0 status to beta in the README

---

gui/multiple_resolutions/main.gd
gui/multiple_resolutions/main.tscn
gui/multiple_resolutions/project.godot

Note that this issue doesn't occur in `3.x` – it may be worth filing an issue on godotengine/godot if someone can create a MRP.

Fix canvas size having a 1-frame delay in Multiple resolutions

---

networking/multiplayer_bomber/bomb_spawner.gd

Needed starting beta11 (godotengine/godot#71129).
Fixes #824

[Net] Fix Multiplayer Bomber custom spawner.

---

gui/multiple_resolutions/README.md

This demo was added to the asset library with release 3.5-9e68af3.

Update multiple resolutions README with an asset library link

---

networking/multiplayer_bomber/bomb.tscn
networking/multiplayer_bomber/player.tscn

This PR fixes #796 and adding outline to player's name label.

Fix bomb spawning above player

---

networking/multiplayer_bomber/bomb.gd

Fix bomb collisions through walls on 3.5

---

networking/multiplayer_bomber/bomb.gd

Fix bomb collisions through walls on 4.0-dev

---

networking/multiplayer_bomber/bomb.tscn

Fix bomb animation

---

2d/pong/project.godot

Fixed that the paddles can cross the floor if you run the "Pong" game in the i3 window manager.

---

networking/multiplayer_bomber/gamestate.gd
networking/multiplayer_bomber/player.gd
networking/multiplayer_bomber/rock.gd
networking/multiplayer_pong/logic/ball.gd
networking/multiplayer_pong/logic/paddle.gd
networking/multiplayer_pong/logic/pong.gd
networking/webrtc_signaling/demo/client_ui.gd
networking/websocket_multiplayer/script/game.gd

I'm looking at the multiplayer examples and they didn't work on Beta16.
See https://github.com/godotengine/godot/issues/72218

Add quotes to rpc flags

---

3d/global_illumination/project.godot
3d/global_illumination/test.tscn
3d/global_illumination/zdm2_all.exr.import
3d/global_illumination/zdm2_indirect.exr.import

This uses lossless compression for EXR lightmaps to prevent overly long import times and decreased quality. The increased memory usage shouldn't be too noticeable since this is a small scene.

Update Global Illumination demo for 4.0.rc1

---

3d/voxel/settings.gd
audio/bpm_sync/bpm_sync.gd
audio/spectrum/show_spectrum.gd

Change warning ignores to use a string identifier

---

misc/os_test/icon.png.import
misc/os_test/os_test.gd
misc/os_test/os_test.tscn

There are additional changes in here from editor automatic changes to the declarative files that are incidental.

Update Operating System Testing demo for 4.0.rc2

---

2d/finite_state_machine/Demo.tscn
2d/finite_state_machine/README.md
2d/finite_state_machine/debug/ControlsPanel.tscn
2d/finite_state_machine/debug/StatesStackDiplayer.tscn
2d/finite_state_machine/debug/states_stack_displayer.gd
2d/finite_state_machine/fonts/SourceCodePro-Black.ttf.import
2d/finite_state_machine/fonts/SourceCodePro-Bold.ttf.import
2d/finite_state_machine/icon.png.import
2d/finite_state_machine/player/Player.tscn
2d/finite_state_machine/player/body.png.import
2d/finite_state_machine/player/shadow.png.import
2d/finite_state_machine/player/states/motion/in_air/jump.gd
2d/finite_state_machine/player/states/motion/on_ground/move.gd
2d/finite_state_machine/player/weapon/sword.gd
2d/finite_state_machine/player/weapon/sword.png.import
2d/finite_state_machine/project.godot
2d/finite_state_machine/state_machine/state_machine.gd

- Fix compilation errors from minor syntax changes
- Fix UI layout
- Fix move_and_slide usage
- Fix zero value conditionals
- Fix run input bindings
- Fix state setter usage
#697

Update finite state machine demo for 4.0.rc4

---

2d/screen_space_shaders/art/filmgrain.png.import
2d/screen_space_shaders/art/vignette.png.import
2d/screen_space_shaders/screen_shaders.tscn
2d/screen_space_shaders/shaders/BCS.gdshader
2d/screen_space_shaders/shaders/blur.gdshader
2d/screen_space_shaders/shaders/contrasted.gdshader
2d/screen_space_shaders/shaders/mirage.gdshader
2d/screen_space_shaders/shaders/negative.gdshader
2d/screen_space_shaders/shaders/normalized.gdshader
2d/screen_space_shaders/shaders/old_film.gdshader
2d/screen_space_shaders/shaders/pixelize.gdshader
2d/screen_space_shaders/shaders/sepia.gdshader
2d/screen_space_shaders/shaders/vignette.gdshader
2d/screen_space_shaders/shaders/whirl.gdshader

Fix `SCREEN_TEXTURE` in "Screen Space Shaders" demo

---

2d/dodge_the_creeps/HUD.gd
2d/dodge_the_creeps/Main.gd
2d/dodge_the_creeps/Mob.gd
2d/dodge_the_creeps/Player.gd
2d/dodge_the_creeps/art/enemyFlyingAlt_1.png.import
2d/dodge_the_creeps/art/enemyFlyingAlt_2.png.import
2d/dodge_the_creeps/art/enemySwimming_1.png.import
2d/dodge_the_creeps/art/enemySwimming_2.png.import
2d/dodge_the_creeps/art/enemyWalking_1.png.import
2d/dodge_the_creeps/art/enemyWalking_2.png.import
2d/dodge_the_creeps/art/playerGrey_up1.png.import
2d/dodge_the_creeps/art/playerGrey_up2.png.import
2d/dodge_the_creeps/art/playerGrey_walk1.png.import
2d/dodge_the_creeps/art/playerGrey_walk2.png.import
2d/dodge_the_creeps/fonts/Xolonium-Regular.ttf.import
2d/dodge_the_creeps/icon.png.import
2d/dodge_the_creeps/project.godot

* Fix `AnimatedSprite2D` (`playing` → `play()`, `frames` → `sprite_frames`).
* `emit_signal("signal_name")` → `signal_name.emit()`.
* Use `Array.pick_random()` instead of `randi() % array.size()`.
* Use `Vector2.clamp()` instead of `clamp()` on components.
* Use `StringName` literals for consistency.
* Switch renderer to Vulkan Mobile to match description in README (this is a bug due to project setting rename).

Update "Dodge the Creeps" demo

---

audio/device_changer/Changer.gd

update names to match new ones

fix getter/setter usage of AudioServer object

---

audio/text_to_speech/voice_list.gd

-id shadowed by function parameter
-delta and new_text never used

audio/text_to_speech demo fixed to work with Godot 4 stable

---

2d/tween/main.gd
2d/tween/main.tscn

Closes #890
Adds extra checkbox, enabled by default:

Add an optional extra RESET step in Tween demo

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

The pull request template was changed to match godotengine/godot's.
See https://github.com/godotengine/godot-demo-projects/issues/697#issuecomment-1509959276.

Add demo submission guidelines

---

LICENSE.md

Just like godotengine/godot#70885 did for the main Godot repository.
Also see https://github.com/godotengine/godot-proposals/pull/6412.

Change copyright year to "present" in LICENSE.md

---

2d/navigation_astar/pathfind_astar.gd
2d/navigation_astar/project.godot

* According to godotengine/godot#74106.

Update "Grid-based Navigation with AStarGrid2D" demo for 4.1

---

mobile/multitouch_view/Main.gd
mobile/multitouch_view/Main.tscn
mobile/multitouch_view/TouchHelper.gd
mobile/multitouch_view/project.godot

change the method and update the project to 4.1

---

3d/physics_tests/project.godot
3d/physics_tests/tests/functional/test_collision_pairs.tscn

edited with v4.2.dev5.official [e3e2528ba]
**before**
**after**
custom_minimum_size x = 230 px
https://github.com/godotengine/godot-demo-projects/assets/41921395/478cf6f0-0cc5-43e0-ac73-aede9fc3cb21

3D Physics Tests, test_collision_pairs, HSlider bugfix

---

3d/graphics_settings/control.tscn
3d/graphics_settings/project.godot
3d/graphics_settings/settings.gd

Limit FPS Slider:
- Min Value = 0 _(no limit)_
- Max Value = 300
- Step = 10
https://github.com/godotengine/godot-demo-projects/assets/41921395/6a7b787b-89c5-4188-ae71-b65d918425d1

3D Graphics Settings, Limit FPS

---

3d/antialiasing/anti_aliasing.gd
3d/antialiasing/anti_aliasing.tscn
3d/antialiasing/project.godot

To see what effect the settings have.

3D Anti-Aliasing, added 'FPS Counter', VSync, Limit FPS

---

2d/physics_platformer/background/parallax_bg.tscn
2d/physics_platformer/coin/coin.tscn
2d/physics_platformer/enemy/enemy.tscn
2d/physics_platformer/project.godot
2d/physics_platformer/stage.tscn

Edited with Godot 4.1.1, only `Scene: Enemy`. The other files Godot has changed automatically.
The 2 'sound nodes' cause the 'can_process' error output. 
... But if they are moved up, then no more, maybe because of `VisibleOnScreenEnabler2D`.

Physics-Based Platformer 2D, fixed "Debugger Errors"

---

networking/webrtc_signaling/client/ws_webrtc_client.gd

Example of "webrtc_signaling" not working on the web
To test, simply configure export for the Web. Run node_server and run the project.
When executed by the editor, everything will work normally,
but if you try to run it in the Browser the connection will not be established.
I investigated the problem and apparently the error is in performing "ws.get_ready_state" before "ws.pool" in the browser;
*Bugsquad edit:* Fixes #983

Example of "webrtc_signaling" not working on the web

---

networking/multiplayer_bomber/bomb.gd
networking/multiplayer_bomber/bomb.tscn
networking/multiplayer_bomber/player.tscn
networking/multiplayer_bomber/project.godot

v4.1.2.stable.official [399c9dc39]
If the bomb and the player are at the same position, then `intersect_ray` returns no result.
`query.hit_from_inside = true`, fixes the problem. The other changes were made automatically by Godot.
https://github.com/godotengine/godot-demo-projects/assets/41921395/fa8123dc-3ba6-4e09-b6fa-4e023d728044

Multiplayer Bomber, fixes PhysicsRayQuery

---

2d/dodge_the_creeps/README.md

Update dodge-the-creeps asset library link

---

networking/multiplayer_bomber/project.godot

change upward movement key to W instead of Z

---

2d/dynamic_tilemap_layers/project.godot
3d/physical_light_camera_units/project.godot
3d/procedural_materials/project.godot
3d/squash_the_creeps/project.godot
compute/texture/project.godot
xr/openxr_character_centric_movement/project.godot
xr/openxr_origin_centric_movement/project.godot

Fixes https://github.com/godotengine/godot-demo-projects/issues/1047
I might be missing some tags, feel free to correct me.

Add missing tags

---

audio/mic_record/MicRecord.gd

This is my first pull request. The title speaks for itself

(Microphone Recording) Use match case instead of if else

---

xr/openxr_character_centric_movement/start_vr.gd
xr/openxr_origin_centric_movement/start_vr.gd

- This closes https://github.com/godotengine/godot-demo-projects/issues/1079.

Fix incorrect typed Array assignment in XR demo scripts

---

3d/voxel/menu/debug.gd
3d/voxel/menu/options/option_buttons.gd
3d/voxel/player/player.tscn
3d/voxel/project.godot
3d/voxel/settings.gd
3d/voxel/world/chunk.gd
3d/voxel/world/voxel_world.gd

Fixes #1180, fixes #1181, also fixes integers getting printed as floats due to the change in Godot 4.4.

Fix block face checks and explicitly define normals in voxel demo

---

networking/multiplayer_bomber/gamestate.gd

Fix nonexistent function error in multiplayer bomber
